sequinstream/sequin

cli/api/webhook_channel.go, cli/cli/webhook_command.go, server/lib/sequin_web/channels/cli_socket.ex, server/lib/sequin_web/channels/webhook_channel.ex, server/lib/sequin_web/controllers/webhook_ingestion_controller.ex
https://www.loom.com/share/737a33a6a2a9485c98ac6d6193329f76?sid=a04b99b4-6d2a-469a-b130-f4b65d3c7318
=> ✨ Webhook Add listens for first message

examples/bash_cpu_metrics/monitor.sh, scripts/cli_tmux_forwarder.sh, spellcheck/project-words.txt
* Add a --with-timestamps option to ./scripts/monitor.sh so one can send many
unique messages
* Add a ./scripts/cli_tmux_forwarder for testing multiple pane sizes
=> 🔧 Improve CLI testing tools

cli/cli/observe_command.go, cli/cli/observe_consumers.go, cli/cli/observe_messages.go
=> 💄 Make tables consistently full width

lib/sequin/consumers/consumer_event.ex, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/receive_consumer_events.sql, test/sequin/consumers_test.exs
=> Refactor max ack pending

assets/js/app.js, mix.exs
This pull request introduces the following changes:
1. Improves code formatting in `assets/js/app.js` by adding semicolons and adjusting indentation for better readability.
2. Modifies the `csrfToken` retrieval to use method chaining for a more concise syntax.
3. Adds the `esbuild` dependency to the project's `mix.exs` file with version "~> 0.8" and sets it to run only in the development environment.
4. Updates the `setup` alias in `mix.exs` to use `cmd npm install --prefix assets` instead of `npm install --prefix assets`, ensuring better cross-platform compatibility.
These changes enhance code style consistency and add a new build tool to the project's development dependencies.
=> Livesvelte setup changes

assets/svelte/databases/Index.svelte, assets/svelte/databases/New.svelte, assets/svelte/databases/NewTopnav.svelte, lib/sequin/changeset.ex, lib/sequin/databases/postgres_database.ex, lib/sequin_web/live/databases/index.ex, lib/sequin_web/live/databases/new.ex, lib/sequin_web/live/databases/show.ex, lib/sequin_web/router.ex
This pull request introduces new functionality for managing databases in the application. Here are the key changes:
1. Added a new Databases Index page that displays a list of databases with their details.
2. Implemented a New Database page with a multi-step form for creating a new database.
3. Created a Database Show page to view detailed information about a specific database, including connection details, configuration, and table information.
4. Added new LiveView modules for handling database-related operations:
- DatabasesLive.Index for listing databases
- DatabasesLive.New for creating new databases
- DatabasesLive.Show for displaying individual database details
5. Updated the router to include new live routes for databases:
- /databases (index)
- /databases/new (create new database) …
=> ✨ Add database management features

assets/svelte/databases/Index.svelte, assets/svelte/databases/New.svelte, assets/svelte/http_endpoints/New.svelte, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/source_table.ex, lib/sequin/consumers_runtime/supervisor.ex, lib/sequin_web/live/databases/new.ex, test/sequin/consumers_test.exs, test/support/factory/consumers_factory.ex
* Fix .value warning
* Ensure http endpoint validation only runs on user input changes
* ditto on databases
=> ✨ Http Endpoint / Datbase polish/bugfixes

lib/sequin/databases/databases.ex, lib/sequin_web/live/home_live.ex, lib/sequin_web/router.ex, lib/sequin_web/user_auth.ex
This pull request introduces a new LiveView module, `SequinWeb.HomeLive`, which creates an animated welcome page for the Sequin application. The page transitions through three states: welcome, connecting, and connected.
Key features:
1. Animated transitions between states with fade-in and fade-out effects.
2. Responsive design with dark mode support.
3. Database connection test and information display.
4. Error handling for failed database connections.
The module includes:
- Mount function to initialize the LiveView.
- Render function with conditional rendering based on the current step.
- Component functions for each step (welcome, connecting, connected).
- Handle_info callbacks to manage state transitions and animations.
- Helper functions for determining the next step and retrieving …
=> ✨ Add HomeLive for database connection animation

assets/svelte/components/TableFilters.svelte, assets/svelte/consumers/HttpPullForm.svelte, assets/svelte/consumers/HttpPushForm.svelte, diff.patch, lib/sequin/consumers/consumer_event_data.ex, lib/sequin/consumers/consumer_record_data.ex, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/source_table.ex, lib/sequin/error.ex, lib/sequin/extensions/replication.ex, lib/sequin/postgres.ex, lib/sequin/replication/message_handler.ex, lib/sequin/string.ex, lib/sequin_web/live/consumers/http_pull_consumer_form.ex, lib/sequin_web/live/consumers/http_push_consumer_form.ex, test/sequin/consumers_test.exs, test/support/factory/consumers_factory.ex
This pull request enhances the table filtering functionality and improves error handling. Key changes include:
1. Updated the `Filter` type to include `columnAttnum` and `valueType` fields.
2. Added support for IS NULL and IS NOT NULL operators, disabling the value input when these are selected.
3. Consolidated `IntegerValue` and `FloatValue` into a single `NumberValue` type.
4. Improved datetime validation in the `DateTimeValue` changeset.
5. Enhanced error traversal and handling in the `Sequin.Error` module.
6. Added a `pg_simple_type_to_filter_type` function to map PostgreSQL types to filter types.
7. Updated the HTTP push consumer form to handle new filter structure and types.
8. Adjusted tests to reflect the changes in filter types and error handling.
9. Minor UI improvements, …
=> ✨ Enhance table filters and error handling

lib/sequin_web/live/home_live.ex
This pull request adds support for handling database connection issues during the initial setup process. Key changes include:
1. Introduced a new `:disconnected` state to handle cases where the database connection fails.
2. Added a `disconnected_component` to display an error message when the database connection is unavailable.
3. Implemented a periodic database connection check when in the disconnected state.
4. Created a reusable `database_config_component` to display database information consistently across different states.
5. Updated the "Get Started" button to be disabled when in the disconnected state.
6. Refactored the `mount` function to handle the new disconnected state and schedule periodic checks.
7. Added a new `handle_info` callback to process the results of periodic …
=> ✨ Add disconnected state handling to HomeLive

assets/svelte/databases/Form.svelte, assets/svelte/databases/Index.svelte, lib/sequin_web/components/layouts/app.html.heex, lib/sequin_web/live/databases/form.ex, lib/sequin_web/live/databases/index.ex
=> Cleanup database index

assets/svelte/consumers/Index.svelte, lib/sequin/consumers/consumers.ex, lib/sequin_web/live/consumers/index.ex
=> Style consumer index

assets/svelte/databases/Index.svelte, assets/svelte/http_endpoints/Index.svelte, lib/sequin/consumers/consumers.ex, lib/sequin_web/live/http_endpoints/index.ex
=> Style http_endpoint index

.gitignore, assets/svelte/components/Sidenav.svelte, assets/svelte/consumers/Index.svelte, assets/svelte/consumers/ShowHeader.svelte, assets/svelte/consumers/ShowHttpPull.svelte, assets/svelte/consumers/ShowHttpPush.svelte, assets/svelte/databases/Index.svelte, assets/svelte/databases/Show.svelte, assets/svelte/http_endpoints/Index.svelte, assets/svelte/http_endpoints/Show.svelte, assets/svelte/utils.ts, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/source_table.ex, lib/sequin_web/live/databases/show.ex
=> Clean up show page styles

assets/svelte/consumers/Index.svelte, assets/svelte/consumers/ShowHttpPull.svelte, assets/svelte/consumers/ShowHttpPush.svelte, assets/svelte/health/HealthComponent.svelte, assets/svelte/health/HealthPill.svelte, config/config.exs, lib/sequin/application.ex, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/http_pull_consumer.ex, lib/sequin/consumers/http_push_consumer.ex, lib/sequin/consumers/source_table.ex, lib/sequin/consumers_runtime/http_push_pipeline.ex, lib/sequin/error.ex, lib/sequin/health/check.ex, lib/sequin/health/health.ex, lib/sequin/json.ex, lib/sequin/replication/message_handler.ex, lib/sequin_web/live/consumers/index.ex, lib/sequin_web/live/consumers/show.ex, lib/sequin_web/live/health_live.ex, test/sequin/health_test.exs, test/support/factory/error_factory.ex, test/support/factory/health_factory.ex
https://www.loom.com/share/924329548e4045588765fb22df0db361
=> ✨ Consumer health check

assets/svelte/components/tracer/Index.svelte, assets/svelte/consumers/Wizard.svelte, lib/sequin_web/live/tracer_live.ex
This fixes hileo's issue with Trace
=> 🐛 Resolve table name to null when table not found

assets/svelte/health/HealthComponent.svelte
Tested for arc, safari, firefox, edge, and chrome
=> 🐛 Fix detached health component for Safari

assets/svelte/databases/Form.svelte, lib/sequin_web/live/databases/form.ex
* moved it below host/port
* added placeholder "postgres"
* added database does not exist to changeset
=> ✨ Rev the database form database field

lib/sequin/consumers_runtime/http_push_pipeline.ex, test/sequin/http_push_pipeline_test.exs
=> :bug: Respect consumer's ack_wait_ms when configuring HTTP push receive_timeout

assets/svelte/consumers/ShowHeader.svelte, assets/svelte/consumers/ShowHttpPush.svelte, assets/svelte/consumers/ShowMessages.svelte, lib/sequin/consumers/consumer_event.ex, lib/sequin/consumers/consumer_record.ex, lib/sequin/consumers/consumers.ex, lib/sequin_web/live/consumers/show.ex
Link to messages with showAcked=false
=> ✨ Show failing messages on consumers tab

config/runtime.exs, docs/self-hosting/docker-compose.mdx, lib/sequin/posthog.ex, lib/sequin_web/components/layouts/root.html.heex
For Sequin Self-hosted, add anonymous telemetry:
* Add ENV variable to opt-out
* Ensure no PII is sent
* Add documentation
=> Add slef-hosted, anonymous telemetry

assets/package-lock.json, assets/package.json, assets/svelte/components/CodeWithCopy.svelte, assets/svelte/components/TableSelector.svelte, assets/svelte/components/ui/sheet/index.ts, assets/svelte/components/ui/sheet/sheet-content.svelte, assets/svelte/components/ui/sheet/sheet-description.svelte, assets/svelte/components/ui/sheet/sheet-footer.svelte, assets/svelte/components/ui/sheet/sheet-header.svelte, assets/svelte/components/ui/sheet/sheet-overlay.svelte, assets/svelte/components/ui/sheet/sheet-portal.svelte, assets/svelte/components/ui/sheet/sheet-title.svelte, assets/svelte/databases/WalProjections.svelte, assets/svelte/wal_projections/Form.svelte, assets/svelte/wal_projections/Index.svelte, assets/svelte/wal_projections/Show.svelte, lib/sequin/databases/databases.ex, lib/sequin/postgres.ex, lib/sequin/replication/message_handler.ex, lib/sequin/replication/replication.ex, lib/sequin/replication/wal_projection.ex, lib/sequin/replication_runtime/wal_event_server.ex, lib/sequin_web/live/wal_projections/form.ex, lib/sequin_web/live/wal_projections/show.ex, test/sequin/message_handler_test.exs, test/sequin/wal_event_server_test.exs, test/support/factory/replication_factory.ex, test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
This pull request introduces a new WAL Projection form component and updates related functionality. Key changes include:
1. Added a new `Form.svelte` component for WAL Projections, providing a user interface for creating and editing WAL Projections.
2. Updated the `CodeWithCopy` component to support different copy icon positions.
3. Enhanced the `TableSelector` component to handle empty search queries.
4. Modified the `Databases` module to include a `update_tables!` function for updating database tables.
5. Extended the `Replication` module to support preloading in the `get_wal_projection_for_account` function.
6. Updated the `WalProjection` schema to separate create and update changesets.
7. Implemented a new `SequinWeb.WalProjectionsLive.Form` module to handle the WAL Projection form …
=> Add WAL Projection form and update related components

lib/sequin/logs/logs.ex
A TODO in the future is to allow for pluggable logger backends.
=> Use file-based logs for self-hosted

assets/svelte/consumers/ShowHttpPull.svelte, assets/svelte/consumers/ShowHttpPush.svelte, lib/sequin/consumers/consumers.ex, lib/sequin/databases_runtime/table_producer_server.ex, lib/sequin/replication/replication.ex, lib/sequin_web/live/consumers/show.ex, test/sequin/consumers_test.exs, test/sequin/wal_pipeline_test.exs
* Require account_id when creating wal pipeline
* Another :filters health on consumers call site
=> ✨ Sequences on consumer show

assets/svelte/settings/AccountSettings.svelte, lib/sequin/accounts/account_user.ex, lib/sequin/accounts/accounts.ex, lib/sequin/accounts/user_notifier.ex, lib/sequin/accounts/user_token.ex, lib/sequin_web/live/settings/account_settings_live.ex, test/sequin/accounts_test.exs
=> feat: add account invitation

lib/sequin/accounts/accounts.ex, lib/sequin/accounts/user_token.ex, lib/sequin_web/controllers/user_session_controller.ex, lib/sequin_web/live/accept_invite_live.ex, lib/sequin_web/live/user_login_live.ex, lib/sequin_web/live/user_registration_live.ex, lib/sequin_web/user_auth.ex, test/sequin/accounts_test.exs
carter/sqn-3366-improve-account-invitation-redirects-and-error-messages
=> ✨ Invitation flow improvements

assets/svelte/consumers/ShowHttpPull.svelte, assets/svelte/consumers/ShowHttpPush.svelte, assets/svelte/consumers/ShowSequence.svelte, config/dev.exs, docs/how-sequin-works.mdx, lib/sequin/consumers/http_pull_consumer.ex, lib/sequin/consumers/http_push_consumer.ex, lib/sequin/consumers/sequence_filter/sequence_filter.ex, lib/sequin_web/live/consumers/show.ex, test/sequin/postgres_replication_test.exs
* Also prevent group column attnums from being updated on consumers by
removing the cast_embed(:sequence_filter) from consumer update
changesets
=> ✨ Show group columns on consumers/show

assets/svelte/consumers/GroupColumnsForm.svelte, lib/sequin/error.ex, test/sequin/error_test.exs
* Auto-expand group column attnums when no pks
* Make form scrollable if many columns
=> 🚨 Show group column attnum errors on consumer forms

assets/svelte/components/FilterForm.svelte, assets/svelte/consumers/GroupColumnsForm.svelte, assets/svelte/consumers/HttpPullForm.svelte, assets/svelte/consumers/HttpPushForm.svelte
Filter and Group Column form components were broken when selectedTable is null
=> 🐛 Consumer form fixes

docker-compose.yaml, lib/sequin/consumers/consumers.ex, lib/sequin/consumers_runtime/consumer_producer.ex, lib/sequin/tracer/state.ex, test/sequin/http_push_pipeline_test.exs
* Push pipeline reduce message counts
* Replication server chunk loading toasts
=> ⚡️ Performance improvements

assets/svelte/components/FilterForm.svelte, lib/sequin/consumers/consumers.ex, lib/sequin/consumers/sequence_filter/column_filter.ex, lib/sequin/extensions/replication.ex, lib/sequin/postgres.ex, test/sequin/postgres_replication_test.exs, test/support/factory/character_factory.ex, test/support/factory/consumers_factory.ex, test/support/models/character_detailed.ex, test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
Note that we do not coerce strings to simulate case-insensitive matching during SQL filtering. That will need to come in a follow-up PR.
=> Add `citext` support

assets/svelte/components/CodeWithSecret.svelte, assets/svelte/consumers/ShowHttpPull.svelte, assets/svelte/databases/Form.svelte, assets/svelte/http_endpoints/Form.svelte, assets/svelte/settings/AccountSettings.svelte, lib/sequin/accounts/accounts.ex, lib/sequin/api_tokens/api_token.ex, lib/sequin/api_tokens/api_tokens.ex, lib/sequin_web/controllers/api_key_controller.ex, lib/sequin_web/live/consumers/show.ex, lib/sequin_web/live/databases/form.ex, lib/sequin_web/live/http_endpoints/form.ex, lib/sequin_web/live/settings/account_settings_live.ex
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/ps7MKmCULkGcazvFyiEe/e1dff82c-d0f8-4517-912a-a7d1fb8e288c.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/ps7MKmCULkGcazvFyiEe/e1dff82c-d0f8-4517-912a-a7d1fb8e288c.mp4">CleanShot 2024-11-07 at 15.02.01.mp4</video>
* Users can create and delete API tokens
* Users can toggle which API token is presented when given API and CLI instructions
=> Add API Token management

lib/sequin/databases/databases.ex
* There is still a small issue- when the job is inserted, Oban is not
running. So the job is not initially run until Oban does a job scan
which can take ~30 seconds. This leaves the db in a waiting state long
enough for a user to see that state.
=> 🐛 Add PostgresDatabaseHealthChecker to create_db_for_account_with_lifecycle

assets/js/app.js, assets/package-lock.json, assets/package.json, config/runtime.exs, lib/sequin_web/components/layouts/root.html.heex
This PR adds Koala telemetry to the console
=> Add koala telemetry to console

assets/svelte/consumers/DestinationKafkaForm.svelte, assets/svelte/types/consumer.ts, lib/sequin/consumers/kafka_destination.ex, lib/sequin/kafka/client.ex, lib/sequin_web/live/components/consumer_form.ex, lib/sequin_web/live/destination_consumers/show.ex, test/sequin/kafka_destination_test.exs
* Removed ssl files for now
* Added sasl_mechanism and updated username/password validation based on
sasl_mechanism
* Added back TLS
* Fixed TLS usage for ipv6 in NetworkUtils
=> 🐛 Fix Kafka connection with sasl_mechanism

assets/svelte/consumers/ShowSink.svelte, assets/svelte/consumers/SinkHttpPushForm.svelte, assets/svelte/consumers/SinkKafkaForm.svelte, assets/svelte/consumers/SinkRedisForm.svelte, assets/svelte/consumers/SinkSequinStreamForm.svelte, assets/svelte/consumers/SinkSqsForm.svelte, lib/sequin/consumers/sink_consumer.ex, lib/sequin/consumers_runtime/kafka_pipeline.ex, lib/sequin/consumers_runtime/redis_pipeline.ex, lib/sequin/consumers_runtime/sqs_pipeline.ex, lib/sequin/consumers_runtime/supervisor.ex
* webhooks and sequin streams get batch size, visibility timeout, etc.
* the stream/queue sinks get nothing
=> ✨ Modify configurable fields for differnt sink consumers

assets/svelte/consumers/ShowSink.svelte, assets/svelte/consumers/ShowSinkHeader.svelte, assets/svelte/consumers/SinkConsumerForm.svelte, lib/sequin/consumers/sink_consumer.ex, lib/sequin_web/live/components/consumer_form.ex
=> :sparkles: Add back 'Change' messages in sink create

assets/svelte/components/FilterForm.svelte, assets/svelte/consumers/SinkConsumerForm.svelte, assets/svelte/wal_pipelines/Form.svelte
carter/sqn-3423-disable-the-ability-to-edit-filters
=> ✨ Disable ability to edit filters

assets/svelte/databases/Index.svelte, lib/sequin/databases/databases.ex, lib/sequin/databases/postgres_database.ex, lib/sequin/databases/sequence.ex, lib/sequin_web/live/databases/index.ex
https://linear.app/sequin/issue/SQN-3430/fix-streams-column-on-databases-page
=> ✨ Show sink consumers count on databases

docs/reference/configuration.mdx
Hello @acco 
Similar to #572 suggesting a change in the doc.
Thanks.
=> Set SECRET_KEY_BASE length to 64 bytes

assets/svelte/settings/AccountSettings.svelte, lib/sequin/accounts/accounts.ex, lib/sequin/accounts/user_token.ex, lib/sequin_web/live/accept_invite_live.ex, lib/sequin_web/live/settings/account_settings_live.ex, lib/sequin_web/live/user_login_live.ex, lib/sequin_web/live/user_registration_live.ex, lib/sequin_web/router.ex, priv/repo/migrations/20241204235903_add_hashed_token_to_user_tokens.exs, test/sequin/accounts_test.exs, test/support/factory/accounts_factory.ex
We don't support sending email in self-hosted Sequin yet. By adding team invite link support, we make it easy for users to invite other team members to their Sequin team.
=> :sparkles: Add team invite links

Makefile, config/dev.exs, docker-compose.yaml, lib/sequin/consumers/consumers.ex, lib/sequin/databases_runtime/keyset_cursor.ex, lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/message_handler_behaviour.ex, lib/sequin/databases_runtime/slot_processor.ex, lib/sequin/databases_runtime/supervisor.ex, lib/sequin/databases_runtime/table_reader.ex, lib/sequin/databases_runtime/table_reader_server.ex, scripts/redis-console-consumer.sh, test/sequin/keyset_cursor_test.exs, test/sequin/postgres_replication_test.exs, test/sequin/table_reader_server_test.exs, test/sequin/table_reader_test.exs
=> ✨ TableReader end-to-end

lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/table_reader.ex, lib/sequin/databases_runtime/table_reader_server.ex, test/sequin/message_handler_test.exs, test/sequin/table_reader_server_test.exs, test/sequin/table_reader_test.exs, test/support/factory/replication_factory.ex, test/support/mocks.ex
=> ♻️ [TableReaderServerTest] Factor out start function

lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/table_reader.ex, lib/sequin/databases_runtime/table_reader_server.ex, test/sequin/message_handler_test.exs, test/sequin/table_reader_server_test.exs, test/sequin/table_reader_test.exs, test/support/factory/replication_factory.ex, test/support/mocks.ex
Preparation for upcoming changes in this file.
=> ♻️ [TableReaderServer] Split cursor into `current_cursor`/`next_cursor`

lib/sequin/databases_runtime/slot_processor.ex, test/sequin/postgres_replication_test.exs
The heartbeat allows us to:
1. Check the health of a slot regularly/deterministically
2. Continuously progress a replication slot/our position in a slot, even if the slot is dormant
Using wal_end as we did previously came with risks.
=> ✨ Add heartbeat message

CONTRIBUTING.md
The instructions were not talking about docker compose and migrations, following them was producing this error:
```elixir
** (Mix) Could not start application sequin: exited in: Sequin.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (RuntimeError) Failed to connect to Redis: %MatchError{term: {:error, {:cannot_connect_to_cluster, [{{:node, ~c"localhost", 6379, :undefined, :undefined}, {:error, :no_connection}}]}}}
(sequin 0.1.0) lib/sequin/redis.ex:43: Sequin.Redis.connect_cluster/0
(sequin 0.1.0) lib/sequin/application.ex:54: Sequin.Application.base_children/0
(sequin 0.1.0) lib/sequin/application.ex:38: Sequin.Application.children/1
(sequin 0.1.0) lib/sequin/application.ex:15: Sequin.Application.start/2
(kernel 10.2) application_master.erl:295: …
```
=> Add missing steps in CONTRIBUTING.md

assets/svelte/consumers/ShowMessages.svelte, lib/sequin_web/live/sink_consumers/show.ex
feature: Support acknowledging messages in a sink
Closes https://github.com/sequinstream/sequin/issues/688
=> feature: Support acknowledging messages in a sink

lib/sequin/consumers/consumer_event.ex, lib/sequin/consumers/receive_consumer_events.sql, lib/sequin/consumers/receive_consumer_records.sql, lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/table_reader_server.ex, lib/sequin_web/live/user_settings_live.ex, priv/repo/migrations/20241230232527_add_group_id_to_consumer_events.exs, test/sequin/consumers_test.exs, test/sequin/message_handler_test.exs, test/sequin/postgres_replication_test.exs, test/support/factory/consumers_factory.ex, test/support/models/character_ident_full.ex, test/support/models/character_multi_pk.ex
* Refactored source_tables out in favor of sequneces
* This resolved a bug that prevented group_id from being set
=> ✨ ConsumerEvent group_id

assets/svelte/consumers/ShowSink.svelte, assets/svelte/types/consumer.ts, lib/sequin/databases_runtime/message_handler.ex, lib/sequin_web/live/sink_consumers/show.ex, test/sequin/message_handler_test.exs
This works when replica identity is set to full
=> ✨ load unchanged_toasts from old

assets/svelte/components/SinkCardNats.svelte, assets/svelte/consumers/SinkNatsForm.svelte, assets/svelte/types/consumer.ts, docs/quickstart/nats.mdx, lib/sequin/consumers/nats_sink.ex, lib/sequin/sinks/nats/client.ex, lib/sequin/sinks/nats/connection_cache.ex, lib/sequin/transforms/transforms.ex, lib/sequin_web/live/components/consumer_form.ex, lib/sequin_web/live/sink_consumers/show.ex, test/tmp/.gitignore
=> feat: add jwt to nats sink

lib/sequin/health/check.ex, lib/sequin/health/health.ex, lib/sequin_web/live/sink_consumers/index.ex, lib/sequin_web/live/sink_consumers/show.ex, test/sequin/postgres_replication_test.exs, test/sequin/wal_pipeline_server_test.exs
https://github.com/user-attachments/assets/48f9c923-1b70-4444-8109-0870e6fba30f
=> 💄 Roll database health into sink consumer health in console

assets/svelte/health/HealthAlerts.svelte, lib/sequin/databases/databases.ex, lib/sequin/databases_runtime/table_reader.ex, lib/sequin/health/check_sink_configuration_worker.ex, lib/sequin/health/health.ex, lib/sequin/postgres.ex, lib/sequin_web/live/databases/form.ex, lib/sequin_web/live/sink_consumers/show.ex
=> 💄 Add Health alert around table missing from publication

assets/package-lock.json, assets/package.json, assets/svelte/components/ui/alert/index.ts, assets/svelte/consumers/ShowSink.svelte, assets/svelte/health/HealthAlerts.svelte, assets/svelte/health/HealthSummary.svelte, assets/svelte/health/Types.ts, config/config.exs, lib/sequin/application.ex, lib/sequin/databases/databases.ex, lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/table_reader.ex, lib/sequin/health/check.ex, lib/sequin/health/check_postgres_replication_slot_worker.ex, lib/sequin/health/check_sink_configuration_worker.ex, lib/sequin/health/event.ex, lib/sequin/health/health.ex, lib/sequin/health/kickoff_check_sink_configuration_worker.ex, lib/sequin/postgres.ex, lib/sequin_web/live/databases/form.ex, lib/sequin_web/live/databases/show.ex, lib/sequin_web/live/sink_consumers/show.ex, test/sequin/health_test.exs, test/sequin/message_handler_test.exs
https://share.cleanshot.com/j2fz8cHp
=> 💄 Add HealthAlerts, CheckSinkConfigurationWorker

assets/svelte/components/Sidenav.svelte, lib/sequin_web/components/sidenav.ex
Not an accurate example, but you get the idea :)
=> 💄 Display a notification if instance not on latest version

lib/sequin/consumers/consumers.ex
=> 🐛 Drop virtual fields for messages, including payload_size_bytes

assets/svelte/consumers/ShowSink.svelte, assets/svelte/consumers/ShowSinkHeader.svelte, assets/svelte/consumers/SinkIndex.svelte, assets/svelte/consumers/StopSinkModal.svelte, assets/svelte/health/HealthSummary.svelte, lib/sequin/consumers/sink_consumer.ex, lib/sequin/consumers_runtime/lifecycle_event_worker.ex, lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/slot_processor.ex, lib/sequin/databases_runtime/slot_supervisor.ex, lib/sequin/health/health.ex, lib/sequin/replication/postgres_replication_slot.ex, lib/sequin/yaml_loader.ex, lib/sequin_web/live/sink_consumers/show.ex, priv/repo/migrations/20250210233021_etst_add_paused_status_to_sink_consumers.exs, test/sequin/health_test.exs
https://share.cleanshot.com/3Nx4Mhhv
=> ✨ Add paused state to sinks

assets/svelte/consumers/ShowSink.svelte, lib/sequin/databases_runtime/slot_message_store.ex, lib/sequin/metrics/metrics.ex, lib/sequin_web/live/sink_consumers/show.ex
https://www.loom.com/share/bc9092d54da24eed862c4cb8438151b3
=> ✨ Bandwidth on sink/show

lib/sequin/databases_runtime/slot_processor.ex
If we've already seen an Insert/Update/Delete before (compared to watermark wal cursor), we can reject it. We should reject it way early in the pipeline, before e.g. decoding it into a Message struct.
=> ⚡In SlotProcessor, hoist up message skipping

lib/sequin/health/health.ex
In the instance where we are processing a large transaction, we won't see our heartbeat message for a whiele. Don't show an error message - receiving messages of any kind indicates slot healthiness.
=> :lipstick: Do not show heartbeat error message if processing messages

lib/sequin/consumers_runtime/consumer_producer.ex
=> ⚡️ Only pass consumer_id to acknowledger

lib/sequin/databases_runtime/slot_message_store.ex, lib/sequin/databases_runtime/slot_message_store_state.ex, lib/sequin/databases_runtime/table_reader_server.ex, test/sequin/slot_message_store_state_test.exs, test/sequin/slot_message_store_test.exs
- Use a materialized set to keep track of unpersisted messages for a given table reader batch
- Notify the TableReaderServer as soon as there are no more unpersisted messages
=> ⚡️ Improve perf of table reader batch checking, use notify/pull pattern

lib/sequin/consumers_runtime/init_backfill_stats_worker.ex, lib/sequin/databases_runtime/table_reader.ex, priv/repo/migrations/20250218222507_alter_rows_intitial_count_to_int8.exs
=> ✨ timeout: :infinity for backfill stats

lib/sequin/databases_runtime/table_reader_server.ex, test/sequin/table_reader_server_test.exs
- Split out and re-organize functions
=> ♻️ Refactor TableReaderServer

lib/sequin/databases_runtime/table_reader.ex, lib/sequin/databases_runtime/table_reader_server.ex
We have a Postgres database that returns wildly different numbers for pg_logical_emit_message/3 and pg_current_wal_lsn/0:
```
select pg_logical_emit_message(true, 'acco-ignore-message', '')
B0234/7C794C04
select pg_current_wal_lsn();
0/471892C8
```
We're not sure why this happens (the message coming through the slot has an LSN that's close to pg_current_wal_lsn). We suspect the way the db was created (replica/standby/copy?). To be safe, we will not trust the LSN that is returned by this function.
=> 🐛 Don't trust the LSN from pg_logical_emit_message/3

lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/slot_processor.ex
=> ⚡️ Remove one mapping over messages in MessageHandler

lib/sequin/databases_runtime/slot_message_store.ex, lib/sequin/databases_runtime/slot_processor.ex
* Use raw_bytes in SlotProcessor
=> ✨ Move more into :put_messages_after_reply

lib/sequin/databases_runtime/slot_processor.ex
=> ✨ Accumulate messages across multiple commits

lib/sequin/databases_runtime/slot_processor.ex
* Preparation for asynchronous msg processing
=> ✨ [SlotProcessor] Handle relation messages inline

lib/sequin/consumers_runtime/consumer_producer.ex, lib/sequin/databases_runtime/message_handler.ex, lib/sequin/databases_runtime/slot_processor.ex, lib/sequin/metrics/metrics.ex, lib/sequin/metrics/store.ex, test/sequin/postgres_replication_test.exs
=> ⚡️ Refactor SP buffering ahead of concurrent flushes

lib/sequin/databases_runtime/table_reader.ex, lib/sequin/databases_runtime/table_reader_server.ex
♻️ [TableReader] Port `fetch_batch_by_primary_keys` from #1003
♻️ [TableReaderServer] Add type TableReaderServer.fetch_task
=> ♻️ [TableReader] Port `fetch_batch_by_primary_keys` from #1003

lib/sequin/postgres/replication_connection.ex, lib/sequin/runtime/slot_message_handler.ex, lib/sequin/runtime/slot_processor_server.ex, test/sequin/slot_message_handler_test.exs
Support actions in ReplicationConnection by changing return tuples
Back pressure improvements: don't crash in SlotMessageHandler when getting back pressure
✨ Improve back-pressure handling by keeping SlotProcessor up
- Add new functionality to ReplicationConnection to allow us to start timers and update state in more areas
- Track the last flushed wal cursor in state
- When we get back pressure error, disconnect don't crash
- On reconnect, filter out messages below the last flushed wal cursor
=> Support actions in ReplicationConnection by changing return tuples

lib/sequin/postgres/replication_connection.ex, lib/sequin/runtime/slot_processor_server.ex, test/sequin/postgres_replication_test.exs
- Add new functionality to ReplicationConnection to allow us to start timers and update state in more areas
- Track the last flushed wal cursor in state
- When we get back pressure error, disconnect don't crash
- On reconnect, filter out messages below the last flushed wal cursor
=> ✨ Improve back-pressure handling by keeping SlotProcessor up

README.md
PostgreSQL and Redis containers are essential for local development, as Sequin will not function without them
=> Add Docker Compose setup mention to README

assets/svelte/consumers/Backfill.svelte, assets/svelte/consumers/ShowSink.svelte, assets/svelte/consumers/SinkIndex.svelte, lib/sequin_web/live/sink_consumers/index.ex
* Make backfill buttons more consistent on show page
* Add a backfill badge on the index page
* Use the backfill icon throughout
=> 💄 Backfill icon

docs/how-to/annotate-changes.mdx, docs/how-to/create-audit-logs.mdx, docs/mint.json, docs/reference/annotations.mdx, docs/reference/messages.mdx, lib/sequin/consumers/consumer_event_data.ex, lib/sequin/consumers/consumer_record_data.ex, lib/sequin/runtime/message_handler.ex
- Annotations should only apply to change messages
- Add and update docs
=> Updates to transaction_annotations, add docs

lib/sequin/transforms/transforms.ex, lib/sequin/yaml_loader.ex
* Azure EventHub sinks !
* Webhook http_endpoint_path
=> 🐛 Add missing params from yaml_loader / transforms

lib/sequin/runtime/wal_pipeline_server.ex
This is from very long ago and safe to remove. Caused strange issues when adding a new feature.
=> 🪦 [WalPipelines] Remove unique index migrations

lib/sequin/runtime/slot_processor_server.ex
When we receive a relation message for a given table for a second time, we can know ~for sure that the table was updated/migrated. So, we can trigger the DatabaseUpdateWorker to run.
This won't work if:
- we weren't connected to the database during the migration
- we were connected to the database during the migration, but we hadn't received any records pertaining to the migrated table prior to the migration (so the relation has not been cached yet)
=> ✨ Trigger database update when new relation message received

assets/svelte/consumers/SinkConsumerForm.svelte, lib/sequin/consumers/sink_consumer.ex, lib/sequin/sinks/redis/client.ex, lib/sequin/transforms/message.ex, lib/sequin/transforms/transforms.ex, lib/sequin/yaml_loader.ex, lib/sequin_web/live/components/consumer_form.ex, priv/repo/migrations/20250328154421_rename_transform_to_legacy_transform.exs, test/sequin/http_push_pipeline_test.exs, test/sequin/yaml_loader_test.exs, test/sequin_web/controllers/pull_controller_test.exs, test/support/factory/consumers_factory.ex
=> ♻️ Rename :transform to :legacy_transform in prepation for path transforms

lib/sequin/application.ex, lib/sequin/transforms/test_messages.ex, lib/sequin_web/live/transforms/new.ex, test/sequin/transform_test_messages_test.exs
=> ⚡️ Use registry to only save test messages when the user is creating a transform

.github/workflows/docker-cloud-build.yml
This reverts commit cf0d60b33b08c8a0183fbf501f2af2b09079c15c.
=> Revert "add image push to GCP"

lib/sequin/consumers/sqs_sink.ex
Related to https://github.com/elixir-lang/elixir/pull/14381
=> fix: move regex out of the module scope

assets/svelte/consumers/SinkConsumerForm.svelte, lib/sequin/consumers/sink_consumer.ex, lib/sequin/enum.ex, lib/sequin/runtime/sink_pipeline.ex, lib/sequin/transforms/transforms.ex, lib/sequin/yaml_loader.ex, lib/sequin_web/live/components/consumer_form.ex, priv/repo/migrations/20250408185138_add_timestamp_format_to_sink_consumers.exs, test/sequin/enum_test.exs, test/sequin/http_push_pipeline_test.exs, test/sequin/yaml_loader_test.exs, test/support/factory/consumers_factory.ex
Validation:
Without it on:
With it on:
=> ✨ Support transforming timestamps to unix (numeric)

lib/sequin/consumers/consumers.ex, lib/sequin/runtime/keyset_cursor.ex, lib/sequin/transforms/transforms.ex, lib/sequin_web/controllers/backfill_controller.ex, lib/sequin_web/controllers/backfill_json.ex, lib/sequin_web/router.ex, test/sequin/transforms_test.exs, test/sequin_web/controllers/backfill_controller_test.exs
=> ✨ management /api for backfills

scripts/start_commands.sh
Copy file (vs edit in place) to avoid permission issues that were appearing on linux machines
=> 💚 Fix config file interpolation

lib/sequin/yaml_loader.ex
For better and worse, we check connectivity to user databases inside YAML config plan/apply. This can lead to long transaction times.
This commit increases that timeout.
A TODO is to move these checks into async processes. (This means database will need to be able to be in a provisioning state, where we haven't yet fetched their tables yet.)
=> 🐛 Increase timeout in plan/apply YAML

assets/svelte/consumers/ShowSinkHeader.svelte
=> Add Docs button to Show Sink page

assets/svelte/transforms/Edit.svelte, lib/sequin/application.ex, lib/sequin/transforms/minielixir.ex, test/sequin/transforms_test.exs
=> 🐛 Prevent race on startup where transforms are loaded in parallel

lib/sequin/runtime/consumer_producer.ex, lib/sequin/runtime/slot_message_store.ex
Under high load, the `SlotMessageStore` process tends to retain large binaries due to message accumulation.  
Because the process stays active, GC is delayed, causing the binary heap to grow uncontrollably.
This PR introduces an optimization to hibernate the `SlotMessageStore` process when there are no more messages to handle.  
Hibernation triggers garbage collection and suspends the process until the next message arrives, or until `ConsumerProducer` checks for messages due to `batch_timeout`.
Additionally:
- Introduced a `messages_processed` message to let consumers reset the `receive_timer` once all messages have been delivered.
- Increased the `batch_timeout` from 10 seconds to 1 minute, as it's primarily a fallback. `SlotMessageStore` triggers processing immediately upon receiving …
=> feat: hibernate slot_message_store when all messages are processed

lib/sequin/runtime/slot_processor_server.ex
When the system hits the memory limit, right now we disconnect right away. By instead giving the system up to 3 seconds to drain below the limit, we can dramatically improve performance in situations where we are near the limit.
The ideal fix is to not pull messages into the system anyway when we're at the limit, but that improvement can come later.
=> ⚡️ Add retry attempts when system is at memory limit

lib/sequin/postgres/array_lexer.ex, lib/sequin/runtime/slot_processor_server.ex, test/sequin/postgres/array_lexer_test.exs
PR 1 / 2
2nd PR extracts the value casting out so we can unit test everything
=> 🐛 Improve parsing of pg arrays

lib/sequin/runtime/typesense_pipeline.ex, lib/sequin/sinks/typesense/client.ex
- actually listen to the batch_size parameter
- fetch! on the timeout_seconds (ecto model defaults it)
- set ignore_not_found to true on deletes
=> typesense: cleanup parameters

docs/how-to/stream-postgres-to-sns.mdx, docs/how-to/stream-postgres-to-sqs.mdx, docs/quickstart/sns.mdx, docs/quickstart/sqs.mdx, docs/reference/sinks/sns.mdx, docs/reference/sinks/sqs.mdx, lib/sequin/yaml_loader.ex
📝 Add AWS to sidebar titles for SNS and SQS
💄 [YAML Loader] Improve error when Postgres table not found in source db
=> 📝 Add AWS to sidebar titles for SNS and SQS

lib/sequin/accounts/accounts.ex, lib/sequin/application.ex, lib/sequin/transforms/minielixir.ex, test/sequin/accounts_test.exs
* Use this for feature_transforms feature
=> ✨ cached_has_feature? for accounts

docs/reference/configuration.mdx, docs/running-sequin.mdx
Improve the docs to clarify what we mean by Redis persistence, and add details for how what permissions a Sequin user needs in an existing postgres database
=> [Docs] Clarify Redis persistence, add user permissions to Postgres

cli/cli/config_command.go
This means that you can run e.g. `./sequin config export > sequin.yaml`
=> cli: print diagnostic message from config export to stderr

assets/svelte/components/CodeWithCopy.svelte, assets/svelte/consumers/Backfill.svelte, assets/svelte/consumers/ShowSink.svelte, assets/svelte/consumers/types.ts, assets/svelte/databases/Form.svelte, assets/svelte/databases/Show.svelte, assets/svelte/health/HealthAlerts.svelte, assets/svelte/health/Types.ts, docs/reference/databases.mdx, lib/sequin/constants.ex, lib/sequin/databases/database_update_worker.ex, lib/sequin/databases/databases.ex, lib/sequin/databases/postgres_database.ex, lib/sequin/health/check_postgres_replication_slot_worker.ex, lib/sequin/health/event.ex, lib/sequin/health/health.ex, lib/sequin/postgres/postgres.ex, lib/sequin/runtime/database_lifecycle_event_worker.ex, lib/sequin/runtime/slot_processor_server.ex, lib/sequin_web/live/databases/form.ex, lib/sequin_web/live/databases/show.ex, lib/sequin_web/live/sink_consumers/show.ex, priv/repo/migrations/20250501215321_add_pg_major_version_to_postgres_databases.exs, test/sequin/postgres_replication_test.exs, test/support/factory/databases_factory.ex, test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
=> ✨ Support Postgres 13

lib/sequin/runtime/table_reader_server.ex
It seems like a fine idea but I don't think was doing what it said
=> Fix comment/code in table_reader_server task

lib/sequin/health/event.ex
Health.Event structs need to have error fields that encodeable/decodeable as JSON. That's usually the case as they are usually Sequin.Error structs. However, we had an instance wherea  Jason.Decode error snuck through, breaking event encoding/decoding.
These situations should be seen as temporary leaks that we ought to fix.
=> 🐛 Handle non-Sequin.Error structs in Health.Events

lib/sequin/replication/replication.ex, lib/sequin/runtime/consumer_lifecycle_event_worker.ex, lib/sequin/runtime/postgres_adapter/decoder.ex, lib/sequin/runtime/slot_processor_server.ex, test/sequin/postgres_replication_test.exs
Reverts sequinstream/sequin#1379
=> Revert "[slotprocessorserver] fast reject messages not destined for any sink"

lib/sequin/transforms/minielixir/validator.ex, test/sequin/minielixir_test.exs
Addressed: https://github.com/sequinstream/sequin/issues/1367
=> feat: accept _{var} in mini-elixir function headers

lib/sequin/yaml_loader.ex, test/sequin/yaml_loader_test.exs
=> Fix transforms YAML flat format

assets/svelte/consumers/ShowMessages.svelte, lib/sequin/health/check.ex, lib/sequin/health/event.ex, lib/sequin/health/health.ex, lib/sequin/runtime/sink_pipeline.ex, lib/sequin/runtime/slot_message_store.ex, lib/sequin/runtime/slot_message_store_state.ex, lib/sequin_web/live/sink_consumers/show.ex, lib/sequin_web/router.ex
=> ✨ Deep link from message delivery error to messages tab

lib/sequin/transforms/minielixir.ex, lib/sequin/transforms/minielixir/validator.ex, test/sequin/transforms_test.exs
closes #1452 
Note that this PR only addresses errors in real life and NOT the transform editor/playground page.
=> [minielixir] propagate line number in errors

docker/replica-cdc-dev/init-primary.sh, docker/replica-cdc-dev/init-replica.sh, lib/sequin/databases/databases.ex
=> ⚙️  Only consider physical replicas as replicas

config/config.exs, lib/sequin/check_system_health_worker.ex, lib/sequin/databases/create_replication_slot_worker.ex, lib/sequin/health/check_postgres_replication_slot_worker.ex, lib/sequin/health/check_sink_configuration_worker.ex, lib/sequin/health/kickoff_check_http_endpoint_health_worker.ex, lib/sequin/health/kickoff_check_postgres_replication_slot_worker.ex, lib/sequin/health/kickoff_check_sink_configuration_worker.ex, lib/sequin/health/snapshot_health_worker.ex, lib/sequin/runtime/consumer_lifecycle_event_worker.ex, lib/sequin/runtime/database_lifecycle_event_worker.ex, lib/sequin/runtime/init_backfill_stats_worker.ex, test/sequin/transforms_test.exs
* Create a few more queues and increase overall queue sizes
=> ⚙️  Oban queues

assets/svelte/components/DeleteFunctionDialog.svelte, assets/svelte/consumers/SinkIndex.svelte, assets/svelte/databases/Index.svelte, assets/svelte/databases/Show.svelte, assets/svelte/transforms/Edit.svelte, assets/svelte/transforms/Index.svelte, lib/sequin_web/live/databases/show.ex, lib/sequin_web/live/transforms/index.ex
Tried to improve the functions UI index page:
Function page fefore:
Functions page after:
=> ⚡️ Improved UI for Functions dashboard. Render publication and replication slot name for the databases index screen as well

lib/sequin/consumers/consumers.ex, lib/sequin/runtime/slot_message_store.ex, lib/sequin/runtime/slot_message_store_state.ex, test/sequin/consumers_test.exs, test/sequin/slot_message_store_test.exs
=> ✨ Respect max memory and storage for SMS.put_messages

lib/sequin/runtime/slot_message_store.ex, test/sequin/slot_message_store_test.exs
=> ✨ pull messages from disk when under half of limits

lib/sequin/runtime/slot_message_store.ex
=> 🐛 Make this safe if MAX_MEMORY_MB is reduced

lib/sequin/transforms/transforms.ex
=> ✨ Ignore encrypted headers instead of returning error

assets/svelte/functions/Edit.svelte, lib/sequin_web/live/functions/edit.ex
- make it possible to select test messages without submitting the form
- don't continuously re-run the function
=> transforms edit page improvements

lib/sequin/transforms/transforms.ex
=> export filter functions in transforms

assets/svelte/functions/Edit.svelte
=> functions page - limit update modal size

lib/sequin/transforms/transforms.ex
this is required for yaml plan to work correctly
=> add annotations to sinkconsumer to_external

cli/constants/constants.go, cli/main.go
=> [cli] remove logging

assets/svelte/functions/Edit.svelte
=> use combobox for table selector on functions edit page

lib/sequin/consumers/consumers.ex, lib/sequin/runtime/message_handler.ex, test/sequin/consumers_test.exs, test/sequin/message_handler_test.exs
Where
c = # of consumers and
m = # of messages
=> ⚡️ Refactor message fan-out to be O(c + m) instead of O(c*m)

docs/reference/configuration.mdx
=> document redis auth in url

scripts/start_commands.sh
=> Fix cli args in start commands for interpolate-from-stdin

assets/svelte/components/TableOrSchemaSelector.svelte, assets/svelte/consumers/SinkConsumerForm.svelte, lib/sequin_web/live/components/consumer_form.ex
Decided to break this out to a new component, the changes were not too
severe so I am considering folding this back into TableSelector
=> 💄 TableOrSchemaSelector

lib/sequin/transforms/transforms.ex, lib/sequin/yaml_loader.ex, test/sequin/yaml_loader_test.exs
=> ✨ Improve error when non-existing column is used for group columns or column filters

lib/sequin/runtime/slot_processor_server.ex
Move all flushing logic to one location. `handle_data` ought to focus on message accumulation. Inside of `:flush_messages` (timer), we can do the flushing. Now, we'll check after receiving messages if we should flush right away. If we should, we'll reschedule the timer for 0.
This is in preperation for soft disconnects/stopping receives from tcp.
=> :recycle: Move flushing out of handle_data

cli/config/config.go
Previously:
```
➜  sequin git:(06-26-_add_routing_mode_into_sink_params) ✗ sequin config apply
sequin: error: server returned error:
code: <nil>
summary: <nil>
validation_errors: map[sink:map[password:[is required when SASL Mechanism is plain] username:[is required when SASL Mechanism is plain]]]
```
With this PR:
```
sequin: error: server returned error: validation_errors:
sink:
username:
- is required when SASL Mechanism is plain
password:
- is required when SASL Mechanism is plain
```
=> 💄 Better formatting for errors from the cli during config apply

lib/sequin/runtime/slot_producer/reorder_buffer.ex
=> ⚡️ Reorder ready batch management

lib/sequin/runtime/slot_producer/slot_producer.ex
* This fixes a bug where accumulated messages could have an assigned
batch_idx that is flushed before those accumulated messages are
dispatched
=> 🐛 Assign %Message{batch_idx: } when producing

assets/svelte/functions/Edit.svelte, assets/svelte/functions/EditableArgument.svelte, assets/svelte/functions/types.ts, lib/sequin/consumers/consumers.ex, lib/sequin_web/live/functions/edit.ex
Right now this is working in a limited fashion for tables with a single
primary key. You cannot edit the messages, nor can you configure which
columns are considered primary keys.
=> ✨ Functions/edit console

assets/svelte/consumers/ShowMessages.svelte, lib/sequin/runtime/slot_message_store.ex, lib/sequin/runtime/slot_message_store_state.ex, lib/sequin_web/live/sink_consumers/show.ex, test/sequin/slot_message_store_state_test.exs, test/sequin/slot_message_store_test.exs
=> 🛠️ Lazily load message data in Messages tab
