- examples/bash_cpu_metrics/load_consumer.sh
- server/lib/sequin/streams/query/receive_for_consumer.sql
- server/lib/sequin_web/channels/observe_channel.ex
* Sort observe consumer messages by seq
* Fix ack success parsing in examples/bash_cpu_metrics/load_consumer.sh
> 🐛 Prevent concurrent receives from delivering same message

- lib/sequin/consumers/consumers.ex
- lib/sequin/replication/message_handler.ex
- priv/repo/migrations/20240626021320_create_initial.exs
- test/sequin/consumer_record_test.exs
- test/sequin/consumers_test.exs
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
This pull request implements support for both event and record message kinds in the replication system. Key changes include:
1. Added handling for `message_kind: :record` in the `MessageHandler`.
2. Updated `insert_consumer_events` and `insert_consumer_records` to handle empty lists.
3. Refactored `MessageHandler.handle_messages/2` to support both event and record message types.
4. Updated tests to cover the new functionality for both event and record message kinds.
5. Improved fan-out logic to correctly distribute messages to consumers based on their message kind preference.
6. Enhanced test coverage to ensure proper handling of mixed message kind scenarios.
7. Optimized database operations by using `Repo.transact` for inserting consumer messages.
8. Updated `ConsumerRecord` creation to …
> Add support for message_kind: record in MessageHandler

- .iex.exs
- lib/sequin/application.ex
- lib/sequin/consumers/consumers.ex
- lib/sequin/replication/message_handler.ex
- priv/repo/migrations/20240626021320_create_initial.exs
- test/sequin/consumer_record_test.exs
- test/sequin/consumers_test.exs
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
- test/support/factory/character_factory.ex
- test/support/models/character_multi_pk.ex
- test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
This pull request addresses several improvements and bug fixes across the Sequin project:
1. Added an alias for Sequin.Repo in .iex.exs for easier access in IEx sessions.
2. Removed Sequin.StreamsRuntime.Supervisor from the application's children list.
3. Optimized the preloading of postgres_database in the put_source_data function to avoid unnecessary database queries during tests.
4. Fixed a pattern matching issue in the put_source_data function when executing Postgrex queries.
5. Updated and improved the ConsumersTest module:
- Enabled previously skipped tests
- Refined test cases for put_source_data function
- Improved error handling and assertions
- Updated helper functions and factory methods
6. Made PostgresReplicationTest async: false to prevent interference with other tests using …
> Fix consumers_test and improve put_source_data handling

- .iex.exs
- lib/sequin/application.ex
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/connection_cache.ex
- lib/sequin/databases/databases.ex
- lib/sequin/replication/message_handler.ex
- priv/repo/migrations/20240626021320_create_initial.exs
- test/sequin/connection_cache_test.exs
- test/sequin/consumer_record_test.exs
- test/sequin/consumers_test.exs
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
- test/support/factory/character_factory.ex
- test/support/factory/databases_factory.ex
- test/support/models/character.ex
- test/support/models/character_detailed.ex
- test/support/models/character_ident_full.ex
- test/support/models/character_multi_pk.ex
- test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
This pull request introduces several improvements to the connection handling and database operations:
1. Added a new `existing_connection/2` function to `ConnectionCache` to retrieve only existing connections without creating new ones.
2. Modified `find_or_create_connection/3` to accept a `create_on_miss` parameter, allowing more control over connection creation.
3. Updated `with_connection/2` in the `Databases` module to use `existing_connection/2` first, falling back to creating a temporary connection if needed.
4. Removed the timeout logic from `with_connection/2`, simplifying the function.
5. Added a new test case for `ConnectionCache` to verify error handling when a connection is not found and `create_on_miss` is false.
6. Updated factory functions in `CharacterFactory` to use more …
> Add existing_connection function to ConnectionCache

- lib/sequin/consumers/consumer_event_data.ex
- lib/sequin/consumers/source_table.ex
- lib/sequin/consumers_runtime/supervisor.ex
- mix.exs
- test/support/dev/dev.ex
This pull request introduces a new development support module and makes minor adjustments to improve the project structure:
1. Adds a new `Sequin.Dev` module in `test/support/dev/dev.ex` to facilitate development setup:
- Provides a `setup/1` function to create necessary resources for development
- Automates the creation of accounts, databases, replication slots, HTTP endpoints, and consumers
- Includes helpful error messages and setup instructions for common issues
2. Updates the `elixirc_paths/1` function in `mix.exs` to include the new `test/support/dev` directory for the `:dev` environment
3. Modifies the `DynamicSupervisor` name in `lib/sequin/consumers_runtime/supervisor.ex` to use a more specific namespace: `ConsumersRuntime.DynamicSupervisor`
These changes aim to streamline the …
> ✨ Add dev setup and support files

- lib/sequin/consumers/consumers.ex
- lib/sequin/consumers_runtime/consumer_producer.ex
- lib/sequin/consumers_runtime/http_push_pipeline.ex
- test/sequin/http_push_pipeline_test.exs
This pull request enhances the HTTP push pipeline for consumers, improving test coverage and adding end-to-end functionality. Key changes include:
1. Made `create_consumer_partition` function public in the Consumers module.
2. Added support for test_pid in ConsumerProducer to allow for sandbox mode in tests.
3. Updated ack function to handle test_pid and send ack messages in test mode.
4. Enhanced HttpPushPipeline to support test_pid for improved testability.
5. Expanded test coverage in HttpPushPipelineTest:
- Added tests for successful event sending to HTTP endpoints.
- Included tests for handling non-200 responses and transport errors.
- Implemented end-to-end tests to verify message flow from Postgres to HTTP endpoints.
These changes improve the robustness and testability of the HTTP …
> ✨ End-to-end test for HTTP push pipeline

- lib/sequin/consumers/consumers.ex
- lib/sequin/metrics/store.ex
- test/sequin/metrics/store_test.exs
> ✨ Ensure messages throughput per min is initially equal to processed count

- assets/svelte/consumers/ShowHttpPull.svelte
- assets/svelte/consumers/ShowHttpPush.svelte
- assets/svelte/databases/Show.svelte
- assets/svelte/http_endpoints/Show.svelte
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/databases.ex
- Move from AlertDialog to Dialog so we have more control over the modals (and don't close them prematurely)
- Move Replication update context into an async Task
> :bug: Improve delete flow

- lib/sequin/consumers/record_consumer_state.ex
- lib/sequin/databases_runtime/keyset_cursor.ex
- lib/sequin/databases_runtime/table_producer.ex
- lib/sequin/databases_runtime/table_producer_server.ex
- lib/sequin/ecto/integer_key_map.ex
- test/sequin/table_producer_server_test.exs
- test/sequin/table_producer_test.exs
- test/support/data_case.ex
- test/support/factory/consumers_factory.ex
- test/test_helper.exs
Use to init instead of situation where we have no min_cursor. Means we always need to always have an initial_min_cursor. This will allow us to start from wherever in a table.
> [row consumer] Add `fetch_first_row`

- assets/svelte/components/Datetime.svelte
- assets/svelte/components/SortAndFilterCard.svelte
- assets/svelte/consumers/HttpPullForm.svelte
- assets/svelte/consumers/HttpPushForm.svelte
- assets/svelte/consumers/Wizard.svelte
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases_runtime/keyset_cursor.ex
- lib/sequin/databases_runtime/table_producer_server.ex
- lib/sequin_web/live/consumers/form.ex
- test/sequin/table_producer_server_test.exs
This pull request enhances the datetime component and improves the consumer configuration process. Here are the key changes:
1. Added an "Autofill from ISO8601" feature to the Datetime component, allowing users to input ISO8601 formatted datetime strings.
2. Updated the SortAndFilterCard component to include a new "Sort and start" section, which allows users to select a sort column and specify where the consumer should start processing records.
3. Modified the HttpPullForm and HttpPushForm components to include the new recordConsumerState field and show the start position form for new consumers.
4. Updated the Wizard component to include the recordConsumerState in the initial form state.
5. Refactored the Consumers module to handle the new recordConsumerState and adjust table producer …
> Add ability to set a row consumer to a specific location

- lib/sequin/consumers/consumers.ex
It's either a bassed in negative batch size or oustanding count is
somehow greater than max ack pending
> 🐛 Debug why batch size might be negative

- lib/sequin/extensions/replication.ex
- test/sequin/postgres_replication_test.exs
Postgres' logical replication does not distinguish between `{}` and `{""}`. Both come through as `{}`.
Here, we add tests for both empty arrays and arrays with empty strings. We expect them to be returned as [].
We fix an issue where `{}` was erroneously processed as `{""}`.
https://chatgpt.com/c/67073168-6904-8006-b82e-df2a5c4ce2eb
> Handle empty arrays properly

- assets/package-lock.json
- assets/package.json
- assets/svelte/components/Sidenav.svelte
- assets/svelte/components/ui/button/index.ts
- assets/svelte/components/ui/command/command-dialog.svelte
- assets/svelte/components/ui/command/command-empty.svelte
- assets/svelte/components/ui/command/command-group.svelte
- assets/svelte/components/ui/command/command-input.svelte
- assets/svelte/components/ui/command/command-item.svelte
- assets/svelte/components/ui/command/command-list.svelte
- assets/svelte/components/ui/command/command-separator.svelte
- assets/svelte/components/ui/command/command-shortcut.svelte
- assets/svelte/components/ui/command/command.svelte
- assets/svelte/components/ui/command/index.ts
- assets/svelte/settings/AccountSettings.svelte
- lib/sequin/accounts/account.ex
- lib/sequin/accounts/account_user.ex
- lib/sequin/accounts/accounts.ex
- lib/sequin/accounts/user.ex
- lib/sequin_web/components/layouts/app.html.heex
- lib/sequin_web/components/sidenav.ex
- lib/sequin_web/live/consumers/index.ex
- lib/sequin_web/live/settings/account_settings_live.ex
- lib/sequin_web/live_helpers.ex
- lib/sequin_web/router.ex
- priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
- test/sequin/accounts_test.exs
- test/support/factory/accounts_factory.ex
Implemented multi-account support for users, allowing them to create and switch between multiple accounts.
- Added a new `users_accounts` join table to support many-to-many relationship between users and accounts
- Modified the `users` table, renaming `account_id` to `current_account_id`
- Updated the Sidenav component to include account switching and creation functionality
- Added a new AccountSettings live view for managing accounts
- Updated various components and functions to work with the new multi-account structure
> Add accounts lifecycle

- lib/sequin/databases/create_replication_slot_worker.ex
- lib/sequin/extensions/replication.ex
- lib/sequin/postgres.ex
Neon databases cull their replication slots after 45min of inactivity. This commit ensures we recreate them, should the db have gone dormant.
Long term, we want to keep track of the LSN that we last ack'd for the rep slot, so we can also rewind the slot on create. And probably turn this into an opt-in option for dev databases.
For now, this level of inactivity is only expected for dev dbs.
> Auto-create replication slots for Neon databases

- lib/sequin/bench/end_to_end.ex
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/postgres_database.ex
- lib/sequin/databases_runtime/keyset_cursor.ex
- lib/sequin/databases_runtime/table_producer.ex
- lib/sequin/extensions/replication.ex
- lib/sequin/replication_runtime/wal_pipeline_server.ex
- lib/sequin/streams/message.ex
- lib/sequin/string.ex
- test/sequin/keyset_cursor_test.exs
- test/sequin/table_producer_test.exs
- test/support/factory/character_factory.ex
- test/support/models/character_detailed.ex
- test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
Postgrex does not automatically convert string UUIDs to binary before querying, nor convert to UTF8 string on load. This means we have to use column types to determine when to do this coercion. However, we were improperly handling situations where the value of a UUID field is null.
s/o to @aglassman for both reporting and identifying the root cause of this issue! :pray:
> :bug: Fix issue with null UUIDs

- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/databases.ex
- lib/sequin/databases/postgres_database.ex
- lib/sequin/postgres.ex
- test/sequin/postgres_test.exs
This pull request refactors and improves the handling of PostgreSQL data in the Sequin application. The main changes include:
1. Moved `tables_to_map` and `cast_rows` (renamed to `load_rows`) functions from `PostgresDatabase` to `Postgres` module for better organization.
2. Enhanced `load_rows` function to handle various data types more effectively:
- Properly converts UUID binary to string format
- Sets non-JSON encodable values to nil
- Preserves nil values for optional UUID fields
3. Updated function calls in `consumers.ex` and `databases.ex` to use the new `Postgres.load_rows` and `Postgres.tables_to_map` functions.
4. Added comprehensive tests for the `load_rows` function in `postgres_test.exs` to ensure correct handling of different data types and edge cases.
These changes improve …
> Refactor Postgres row loading and table mapping

- config/config.exs
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/databases.ex
- lib/sequin/databases/enqueue_database_update_worker.ex
- lib/sequin/databases/postgres_database.ex
- lib/sequin/postgres.ex
- test/sequin/postgres_test.exs
This pull request introduces a new scheduled task to periodically update databases. It adds a cron job configuration to Oban in `config/config.exs`, which runs every 6 hours. The new `EnqueueDatabaseUpdateWorker` module is created to handle this task, iterating through all databases and enqueueing individual update jobs for each one. This enhancement ensures regular database updates without manual intervention.
> Add cron job for periodic database updates

- config/config.exs
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/database_update_worker.ex
- lib/sequin/databases/databases.ex
- lib/sequin/databases/enqueue_database_update_worker.ex
- lib/sequin/databases/postgres_database.ex
- lib/sequin/postgres.ex
- test/sequin/consumers_test.exs
- test/sequin/postgres_test.exs
This pull request introduces a new DatabaseUpdateWorker module and enhances error handling for database queries. The changes include:
1. A new DatabaseUpdateWorker module that uses Oban for job processing, allowing for database table updates to be queued and executed asynchronously.
2. Enhanced error handling in the Postgres.query/4 function. When an undefined column error occurs, it now enqueues a database update job using the DatabaseUpdateWorker.
3. Updated tests to verify the new behavior, including an assertion to check if the DatabaseUpdateWorker job is enqueued when an undefined column error is encountered.
These changes improve the system's ability to handle database schema changes by automatically triggering updates when encountering column-related errors during queries.
> Enqueue database update on undefined column error

- config/config.exs
- lib/sequin/consumers/consumers.ex
- lib/sequin/databases/database_update_worker.ex
- lib/sequin/databases/databases.ex
- lib/sequin/databases/enqueue_database_update_worker.ex
- lib/sequin/databases/postgres_database.ex
- lib/sequin/databases_runtime/table_producer.ex
- lib/sequin/postgres.ex
- test/sequin/consumers_test.exs
- test/sequin/postgres_test.exs
- test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
This pull request enhances the handling of database column types in select queries. The main changes include:
1. Introduced a `safe_select_columns` function in the Postgres module to filter and select only columns with available Postgrex encoders.
2. Updated select queries in `Consumers` and `TableProducer` modules to use `safe_select_columns` instead of selecting all columns with `*`.
3. Added a list of safe column types and a `has_encoder?` function to determine which column types can be safely encoded.
4. Modified the behavior for handling non-existent columns in the `ConsumersTest`. Instead of silently ignoring the column, it now returns an error.
5. Added a new `net_worth` column of type `:money` to the test table in the migration file.
These changes improve the robustness of …
> Filter out columns that don't have a Postgrex encoders

- README.md
- assets/svelte/components/Sidenav.svelte
- assets/svelte/components/TableSelector.svelte
- assets/svelte/databases/WalProjections.svelte
- assets/svelte/wal_pipelines/Form.svelte
- assets/svelte/wal_pipelines/Index.svelte
- assets/svelte/wal_pipelines/Show.svelte
- docs/capture-changes/wal-pipelines.mdx
- lib/sequin_web/live/wal_pipelines/form.ex
- lib/sequin_web/live/wal_pipelines/show.ex
- lib/sequin_web/router.ex
Renamed "WAL Pipelines" to "Change Capture Pipelines" across the application and documentation.
- Updated all UI references from "WAL Pipelines" to "Change Capture Pipelines"
- Modified navigation links and routes from `/wal-pipelines` to `/change-capture-pipelines`
- Updated some documentation to reflect the new terminology (replacing the rest in another PR)
- Changed button labels and form titles to use the new naming
- Updated external documentation links to use the new terminology
The term "Change Capture Pipelines" better describes the feature's functionality and is more accessible to users who may not be familiar with WAL (Write-Ahead Logging) terminology. This change makes the feature more intuitive and easier to understand while maintaining all existing functionality.
> Rename "WAL Pipelines" to "Change Capture Pipelines"

- docs/introduction.mdx
Hi there! Found the issue with the embed, the HTML given from the Wistia site is not valid JSX, so the markdown parsing broke. 
I fixed it in this PR to replace the `<iframe>`. Just the style props were broken (since HTML has strings for style props instead of objects which JSX takes), and the `onLoad` props which had a string instead of Javascript.
Thank you!
> Use original Wistia embed without `<iframe>`

- docs/how-to/create-audit-logs.mdx
- docs/how-to/deploy-to-production.mdx
- docs/how-to/maintain-caches.mdx
- docs/how-to/replicate-tables.mdx
- docs/how-to/stream-postgres-to-a-webhook-endpoint.mdx
- docs/how-to/stream-postgres-to-kafka.mdx
- docs/how-to/stream-postgres-to-redis.mdx
- docs/how-to/stream-postgres-to-sequin-stream.mdx
- docs/how-to/stream-postgres-to-sqs.mdx
Added documentation for deploying Sequin to production and improved the cache maintenance guide. Key changes:
- Added new guide explaining how to export local Sequin configuration and apply it to production environments using the CLI
- Restructured cache maintenance guide to focus on change data capture patterns
- Added architecture overview and detailed implementation examples for cache updates
- Improved guidance around message ordering and handling race conditions
- Added sections on maintenance tasks like cache re-warming
- Added placeholders for additional Redis Streams documentation and Kafka configuration details
The deploy guide includes step-by-step instructions for exporting configurations and safely applying them to production, with warnings about environment-specific …
> :sparkles: Add production deployment guide

- docs/self-hosting/docker-setup.mdx
The doc mistakenly mentions the length of SECRET_KEY_BASE as 32 byte long. It should 64 byte long.
> Set SECRET_KEY_BASE length to 64 bytes

- config/config.exs
- lib/sequin/consumers/consumer_event.ex
- lib/sequin/consumers/consumer_record.ex
- lib/sequin/extensions/replication.ex
- lib/sequin/replication/message.ex
- lib/sequin/replication/message_handler.ex
- lib/sequin/replication/wal_event.ex
- priv/repo/migrations/20241205004309_add_seq_to_consumer_stream_tables.exs
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
- test/support/factory/consumers_factory.ex
- test/support/factory/replication_factory.ex
We're propagating `seq` through the pipeline, which is a unique, monotonically increasing integer for each message.
> :sparkles: Add `seq` to consumer messages tables

- docs/reference/sequin-yaml.mdx
Docker container stops when using the example configuration from the docs due to the incorrect destination type
```
** (FunctionClauseError) no function clause matching in Sequin.YamlLoader.parse_sink/2 
```
> [Docs] Fix example configuration

- lib/sequin/databases_runtime/message_handler.ex
- lib/sequin/databases_runtime/table_reader.ex
- lib/sequin/databases_runtime/table_reader_server.ex
- test/sequin/message_handler_test.exs
- test/sequin/table_reader_server_test.exs
- test/sequin/table_reader_test.exs
- test/support/factory/replication_factory.ex
- test/support/mocks.ex
For ultimate safety: the TableReaderServer will now check on occasion to see if it's waiting for a batch to flush, but that batch's LSN is behind the slot's current LSN. i.e. - it's waiting for a batch that will never be flushed, as it already missed.
You'll see in the next PR that we also try to have SlotProcessor discard the batch if it sees the high watermark but didn't see the corresponding low watermark.
> ⚡️ [TableReaderServer] If a batch is missed, discard it

- config/config.exs
- config/dev.exs
- config/prod.exs
- lib/console_logger.ex
Before, we weren't including metadata in log output (in dev or self-hosted prod!) This commit includes all metadata in our log output. We display metadata as `key=value` after the message.
To do so, we're particular about what keys we display. In dev, we don't need keys like `:domain` or `:application` - just noise. But in prod, it's useful to include those, as users will likely use to discriminate Sequin logs from other logs piping into their system.
For a list of the default metadata keys, see the comment in `lib/console_logger.ex`.
> ✨ Improve logs with metadata

- assets/svelte/components/TableSelector.svelte
This small change improves the UI by sorting the `filteredTables` variable by schema and name. The update ensures a more organized and predictable table display for better user experience.
before:
after:
> Sort tables by schema and name on "Create * Sink" page

- assets/svelte/consumers/SinkIndex.svelte
👋 
This PR improves wording on the first page shown after registration.
The component always uses "a" so the easiest fix was to use a singular entity name.
> ✏️ Fix typo: a Sinks -> a Sink

- lib/sequin/databases_runtime/slot_message_store.ex
- lib/sequin/databases_runtime/starter.ex
* This prevents a bug where a single failing replication slot prevents
other replication slots / table readers from starting up
> 🔨 Start replication/table readers with catch

- lib/sequin/databases_runtime/wal_pipeline_server.ex
- lib/sequin/health/event.ex
- lib/sequin/health/health.ex
Previously in WALPipeline we only tracked health events around inserting to the destination. In this PR we now track health events around fetching from our database and deleting from our database period. This will ensure that ephemeral fetch errors won't stick on the health of a WALPipeline indefinitely. they will clear the next time a successful fetch happens.
> :lipstick: Improve WalPipeline health/recovery

- assets/svelte/databases/Show.svelte
- lib/sequin/databases/databases.ex
- lib/sequin/health/check.ex
- lib/sequin/health/check_postgres_replication_slot_worker.ex
- lib/sequin/health/event.ex
- lib/sequin/health/health.ex
- lib/sequin/metrics/metrics.ex
- lib/sequin/metrics/store.ex
- lib/sequin/replication/replication.ex
- lib/sequin_web/live/databases/show.ex
- test/sequin/replication_test.exs
We show the warning at **2GB**
Copy-pasta from how we augment alerts in SinkConsumer. Figured we could get away with it for a _little_ longer.
We'll need some design help to figure out how to organize these alerts and gauges on the console.
**NOTE**: I down-cased `MB` -> `mb` in the console to match `ms` after these screenshots:
> ✨ Add replication lag health checks, console gauge

- cli/cli/context_command.go
Currently, the CLI context picker splits the selected context name on white spaces, grabbing only the first part. The consequence of this is that when, for example, a context is picked for removal and its name contains spaces, the CLI will try to delete a file that doesn't exist or, even worse, an existing file that was not meant to be deleted.
For example, considering a context created with the name "local test", when attempting to remove it via the selector list will result in the CLI trying to remove the file `/home/$HOME/.sequin/contexts/local.json` instead of `/home/$HOME/.sequin/contexts/local test.json`
I don't see why, as the choice variable that contains the context name doesn't contain anything else. Perhaps it's a leftover from a previous iteration when choice had more than …
> Fix picking context names that contain spaces

- assets/svelte/consumers/SinkConsumerForm.svelte
- lib/sequin/consumers/consumers.ex
- lib/sequin/consumers/sink_consumer.ex
- lib/sequin/consumers_runtime/lifecycle_event_worker.ex
- lib/sequin/databases_runtime/slot_message_store.ex
- lib/sequin/databases_runtime/slot_message_store_state.ex
- lib/sequin/size.ex
- lib/sequin_web/live/components/consumer_form.ex
- priv/repo/migrations/20250213215937_add_max_memory_mb_to_sink_consumers.exs
- test/sequin/consumers_test.exs
- test/sequin/slot_message_store_state_test.exs
- test/support/factory/consumers_factory.ex
Allows for configuring a max_memory_mb per consumer in self-hosted environments. Sequin will set a soft memory limit on a consumer based on a consumer's max_memory_mb and the system's configured MAX_MEMORY_MB (whichever is lesser).
> Add `Consumers.max_memory_mb`

- CONTRIBUTING.md
This PR addresses an issue first-time contributors of the project might come across.  One caveat was that I was not able to run the `make signoff` call because it was failing locally. 
I was going through the Contribution page. When running `mix setup`, you may encounter an error if the default PostgreSQL user "postgres" does not exist. This can be resolved by running `createuser -s postgres`. This step is only required once.
```
[error] Postgrex.Protocol (#PID<0.561.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
```
> Add verbiage in Contributions page for needed pguser 

- Dockerfile.postgres
- docker-compose.yaml
Before: `mix test` was failing because docker image did not have the vector extension. This PR builds a pg container with vector and uses that image. 
After: `mix test` passes. 
To test: 
docker compose down
docker compose build
docker compose up
run `mix test`
> Add vector extension to docker image so mix test can pass

- lib/sequin/databases_runtime/message_handler.ex
- lib/sequin/databases_runtime/table_reader.ex
- lib/sequin/databases_runtime/table_reader_server.ex
- test/sequin/table_reader_test.exs
- test/support/factory/character_factory.ex
- test/support/factory/factory.ex
- Support multiple replication slots on one database by tagging each watermark with a replication_id
- More assertive handling of situation where we receive a flush_batch after already having flushed the batch
> 🐛 [TableReaderServer] Tag watermarks with replication_id

- docs/snippets/quickstart-initial-steps.mdx
What This PR Does:
1.	Updates the number of containers running after docker ps—now two instead of three.
2.	Updates the PostgreSQL image version displayed.
> Updated quickstart docs to reflect "docker ps" output

- cli/cli/cli.go
- cli/cli/table.go
Going through the code and removed unused const and type.  No logic changes. 
Note, I was not able to run `make signoff` because it failed locally with the following error:
[error] [06:42:10.042] Postgrex.Protocol (#PID<0.5759.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) sorry, too many clients already line=107 pid=<0.5759.0> mfa=DBConnection.Connection.handle_event/4 
I _was_ able to run `make build` and the CLI built fine after the changes.
> Removed unused const and type

- lib/sequin/consumers/consumers.ex
- lib/sequin/tracer/server.ex
- test/sequin/consumers_test.exs
* This resolves a bug where the Posthog Telemetry Reporter detaches due
to `key :bytes_processed not found`
* This also resolves a bug where messages stored in Postgres are counted
twice towards message throughput / count
> 🐛 Clean up Metrics for acked messages

- assets/svelte/consumers/Backfill.svelte
- lib/sequin/application.ex
- lib/sequin/databases_runtime/message_handler.ex
- lib/sequin/databases_runtime/message_handler_behaviour.ex
- lib/sequin/databases_runtime/slot_processor.ex
- lib/sequin/databases_runtime/table_reader_server.ex
- lib/sequin/ets_multiset.ex
- test/sequin/ets_multiset_test.exs
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
- test/sequin/table_reader_server_test.exs
Instead of accumulating primary keys in MessageHandler.Context, use TableReaderServer.seen_pks
To create a batch, TableReaderServer first fetches a list of PKs for its current cursor. It stores them in a public ETS table. Then makes a subsequent fetch to fetch the whole batch, writing a high watermark when it's done.
In the time before receiving the high watermark and flushing the batch, the system (SlotProcessor) will call `TableReaderServer.pks_seen`. This will drop PKs in the set from the set.
Then when the high watermark arrives, the SlotProcessor will call the TableReaderServer to flush the batch. Before flushing the batch, the batch is filtered out against the PK list. PKs that were seen during processing/change capture will be dropped from the batch, ensuring we do not have any …
> ♻️ Refactor TableReaderServer pk filtering

- .iex.exs
- lib/sequin/databases_runtime/message_handler.ex
- lib/sequin/databases_runtime/message_handler_behaviour.ex
- lib/sequin/databases_runtime/slot_processor.ex
- lib/sequin/databases_runtime/table_reader_server.ex
- test/sequin/message_handler_test.exs
- test/sequin/postgres_replication_test.exs
We need to call `pks_seen` synchronously, before flushing a TableReaderServer batch. This solution (temp) moves the call out of soon-to-be-async handle_messages and into another callback.
> :recycle: Prepare for async message handler by adding before_handle_messages

- lib/sequin/databases/connection_cache.ex
- lib/sequin/runtime/consumer_lifecycle_event_worker.ex
- lib/sequin/runtime/database_lifecycle_event_worker.ex
- lib/sequin/runtime/slot_supervisor.ex
- lib/sequin/runtime/supervisor.ex
After a sink_consumer is updated, we need to restart the ConsumerProducer/Pipeline. In order to do that, we need to restart the SMS+CP pair, and therefore need to restart the SlotProcessor.
> :bug: Restart replication after sink_consumer update

- lib/sequin/health/check_postgres_replication_slot_worker.ex
- lib/sequin/load_generator.ex
- lib/sequin/replication/replication.ex
- lib/sequin/runtime/slot_processor.ex
- lib/sequin/runtime/slot_processor_server.ex
- lib/sequin_web/controllers/postgres_replication_controller.ex
- test/sequin/slot_processor_test.exs
- Move Begin and Commit messages to SlotProcessor
- Handle LogicalMessages up higher (as we want to schedule timers for heartbeats)
- Get rid of process_message - not necessary anymore, as we can now build UndecodedMessages along with their commit information (commit_lsn, commit_idx, etc)
By hoisting up Begin and Commit messages to happening right away, we can do more inside Flow when flushing messages.
> ♻️ Move rest of message handling from SlotProcessorServer -> SlotProcessor

- lib/sequin/health/check_postgres_replication_slot_worker.ex
- lib/sequin/load_generator.ex
- lib/sequin/postgres/postgres.ex
- lib/sequin/runtime/postgres_adapter/decoder.ex
- lib/sequin/runtime/slot_processor.ex
- lib/sequin/runtime/slot_processor_server.ex
- test/sequin/postgres_test.exs
- test/sequin/slot_processor_test.exs
Speed up SlotProcessor by only updating Health during flushes
Note we already do the message_processed update event inside flush_messages, the other one in process_messages was unnecessary.
While we debounce health updates with an ETS lookup, even debounced updates appear to have a cost. By moving the update events into flush_messages, we call them far less frequently on high-throughput slots. This resulted in a 10-15% speed-up.
We could perhaps further optimize in the future by using Process k/v for debouncing, or keeping some "flush messages" generation/idx to debounce more.
♻️ Reorganize/tidy SlotProcessorServer.State
♻️ [SlotProcessorServer] Tidy process_message function
♻️ Add Statsd to CheckPostgresReplicationSlotWorker
🐛 [SlotProcessorServer] Use parent table_name and schema when …
> SlotProcessor clean-up

- lib/sequin/bench/bench.ex
- lib/sequin/postgres/replication_connection.ex
- lib/sequin/redis.ex
- lib/sequin/runtime/consumer_producer.ex
- lib/sequin/runtime/message_handler.ex
- lib/sequin/runtime/slot_message_store.ex
- lib/sequin/runtime/slot_processor_server.ex
- lib/sequin/runtime/table_reader_server.ex
- lib/sequin/sinks/redis/client.ex
- lib/sequin/statsd.ex
- lib/sequin_web/controllers/pull_controller.ex
- test/sequin_web/controllers/pull_controller_test.exs
The `timer.tc` function has [supported time units](https://github.com/erlang/otp/blob/05737d130706c7189a8e6750d9c2252d2cc7987e/lib/stdlib/src/timer.erl#L578) since Erlang 26. 
Because the [`.tool-versions` file](https://github.com/sequinstream/sequin/blob/f3cf9b2772aaa954d4eaa66f9377338d9c9c02e9/.tool-versions#L2) requires Erlang 27.2.1, using `timer.tc` with the `:millisecond` argument is safe and eliminates the need for unnecessary conversions.
> Add time units to timer.tc calls

- lib/sequin/health/event.ex
- lib/sequin/health/health.ex
- lib/sequin/runtime/message_handler.ex
- lib/sequin_web/live/sink_consumers/show.ex
When we receive a bad annotation (unparseable JSON), log a health event. Propagate up to frontend. When the user dismisses it, wait 24h before showing it again (in the case that we're still receiving unparseable JSON).
> Transaction annotations: Add dismissable health event when we receive an invalid annotation

- assets/svelte/components/Sidenav.svelte
- assets/svelte/components/TableSelector.svelte
- assets/svelte/consumers/SinkHttpPushForm.svelte
- assets/svelte/consumers/SinkIndex.svelte
- Changed the "Manage user" icon from `Cog` to `UserCog` in the sidenav for better semantic representation
- Enhanced the database refresh button in TableSelector:
- Simplified Refresh to an icon-only button with proper aria-label
- Added a "Connect new database" button with link to /databases/new
- Improved the sink selection dialog to support more options on a smaller screen
These changes improve usability and provide clearer visual cues for common actions.
> Clean up UX in nav, sink select, db create

- lib/sequin/runtime/postgres_relation_hash_cache.ex
- lib/sequin/runtime/slot_processor_server.ex
Howdy Sequin team! Here is a proposal to fix #924
Main points:
- Add longer-lived schema hash storage in Redis using `HGET` + `HSET`
- Remove `unique_period` to avoid Oban skipping queue job due to throttling
Please let me know if there are better ways to do things, happy to adjust things.
I wanted to add automated testing for this, but I am still fighting to get my postgres+pgvector up and running. I did however run some manual tests changing table schemas and creating/updating records by hand. Any pointers in this direction of automated testing are also more than welcome.
> Refresh database table schema when a relation message with updated schema arrives at stot

- assets/svelte/components/TableSelector.svelte
Added a check icon to indicate the currently selected table in the TableSelector component.
Added a conditional rendering block that displays a green check icon when a table is selected in the TableSelector component. The check icon appears only for the table that matches the `selectedTableOid`.
1. Navigate to a page that uses the TableSelector component
2. Select a table from the list
3. Verify that the selected table now displays a green check icon instead of the default table icon
This change improves the user experience by providing a clear visual indicator of which table is currently selected in the interface, making it easier for users to identify their selection at a glance.
> Make it easier to see selected table

- config/config.exs
- config/prod.exs
- config/runtime.exs
- config/test.exs
- lib/sequin/config_parser.ex
- test/sequin/config_parser_test.exs
Load logger level from env var `LOG_LEVEL` for all environments except test
Some notes:
- We keep the default `:info` level within [`ConfigParser.log_level/1`](https://github.com/sequinstream/sequin/blob/main/lib/sequin/config_parser.ex#L12-L18)
- We keep a hardcoded `:warn` log level for tests to reduce verbosity
> Load logger level from LOG_LEVEL for all environments and adjust defaults

- lib/sequin/health/check_sink_configuration_worker.ex
- lib/sequin/health/health.ex
- lib/sequin/postgres/postgres.ex
- lib/sequin_web/live/sink_consumers/show.ex
- test/sequin/postgres_test.exs
- Check not only the replica identity of the root table, but also its children
- If the replica identity is not "full" in a partition situation, display a different error message
> :lipstick: Improve replica identity check when a table is partitioned.

- lib/sequin/runtime/wal_pipeline_server.ex
- test/sequin/wal_pipeline_server_test.exs
In Change Retentions, we would coalesce events that impacted the same PK inside of a transaction. Now, we generate a unique `seq` by combining the LSN and the commit idx - no longer coalescing.
> 🐛 In change retention, don't coalesce wal events for same record

- lib/sequin/transforms/minielixir/validator.ex
- test/sequin/minielixir_test.exs
When we added the additional allows for Kernel functions, we forgot to include to_string!
> Bring back Kernel.to_string

- lib/sequin/runtime/slot_processor_server.ex
- test/sequin/postgres_replication_test.exs
First, there was an if statement that was returning a tuple that was actually unused.
Second, when we've hit system memory limits, we should undergo the same behavior as when payload limit is exceeded: we should disconnect instead of crashing. Disconnecting is less dramatic, as we preserve our `last_flushed_lsn`, which means we can skip messages rapidly on reconnection.
> ⚡️ [SlotProcessorServer] Disconnect, don't stop, if at system mem limit

- lib/sequin/runtime/consumer_producer.ex
- lib/sequin/runtime/slot_message_store.ex
SMS broadcasts when we ingest new messages. This prompts ConsumerProducer to schedule a pull to check for new messages.
However, there's another scenario where messages will be made available: when messages are *acked*. In that situation, a message that was previously blocked may be available for pulling.
So, we broadcast when that happens as well. Otherwise, you can see a weird pattern where a message belonging to the same group ID as a previous messages takes several seconds to deliver after its counterpart delivers.
Addresses #1327
> Check for recently unblocked messages after ack

- assets/svelte/consumers/SinkConsumerForm.svelte
- lib/sequin/consumers/sink_consumer.ex
Lowering to 128MB – this is a better default experience for Sequin that significantly reduces risk that a Sequin instance will OOM under high load.
Larger deployments of Sequin will want to set this value to a higher number to keep downstream sink workers saturated.
> ⚡Change default soft memory limit for sinks

- Makefile
- mix.exs
This change improves the development experience by modifying the make dev command to start the application via the Interactive Elixir shell. This allows developers to interact with the running system directly from the terminal.
Additionally, :observer has been added to extra_applications in mix.exs, enabling runtime inspection and debugging tools like the Observer GUI.
> chore: start iex shell via make dev and include observer in extra apps

- assets/svelte/components/ui/card/expandable-card.svelte
- assets/svelte/components/ui/card/index.ts
- assets/svelte/consumers/GroupColumnsForm.svelte
- assets/svelte/consumers/SinkConsumerForm.svelte
Hello!
Here we add an `ExpandableCard` component which handles the proper UI behavior for these type of cards. And implement usages of it in SinkConsumerForm, and GroupColumnsForm. This fixes issue #1288.
Additional notes:
- To avoid confusion, now the ChevronDown is hidden from the Card title if the card is in disabled state, such as when no table is selected when creating or editing a sink
- Also fixes a bug where if a table is not selected, it didn't show the "Please select a table first." message in each section.
- Because the `ExpandableCard` component may show a summary or a content fragment depending on the state of the card, I opted to use named slots via svelte:fragment tags, instead of a single slot that handles those state variants. Hopefully thats fine.
- I had to add some …
> feat: add ExpandableCard component and use it in SinkConsumerForm

- lib/sequin/consumers/consumer_event_data.ex
- lib/sequin/consumers/consumer_record_data.ex
- lib/sequin/runtime/message_handler.ex
- lib/sequin/runtime/table_reader.ex
- test/sequin/table_reader_test.exs
> feat: add idempotency_key

- lib/sequin/runtime/slot_message_store.ex
When a SMS is backing up, 10min can be too long to flush in order to advance the slot.
> Decrease flush interval

- lib/sequin/network_utils.ex
Show clearer error messages when performing checks for IPv6 hosts, and also perform additional check if machine has any IPv6 assigned to any network interface as a way to determine machine support.
Notes:
- I have only tested with ISP/networks not supporting IPv6, and manually disabling IPv6 for my network interface, however and I am actively looking for a way to test this with a machine with actual full non-IPv6 support. Any ideas are welcome.
- Another additional approach would be to try to open a socket and bind it to a IPv6 address, but I am yet unsure if it provides any benefit over checking network interface support.
- All tests were performed in the Connect Database page
- In the case of performing a connectivity test to an IPv6 host, we need to mainly catch the `:ehostunreach` - …
> feat: show clearer connectivity errors and run extra checks for IPv6

- lib/sequin/sinks/redis/client.ex
The `qp/2` function is private, so it doesn't work when called via mfa. Probably need to add more tests to cover all such cases 🤦🤦🤦
> fix: put back execution redis command in fun

- lib/sequin/consumers/consumers.ex
- lib/sequin/runtime/slot_message_store.ex
- test/sequin/consumers_test.exs
- test/sequin/slot_message_store_test.exs
We let you set a max memory for Sequin (defaults to ~80% of avail memory) or for individual slot message stores.
Prior behavior was to do min( max_memory/count_sms , sms_max ). This change removes that - we'll let an SMS fill up to his max, so long as the system can support it.
> Don't factor max system memory into individual SMS maxes

- assets/svelte/components/CodeWithCopy.svelte
- assets/svelte/components/FullPageForm.svelte
- assets/svelte/consumers/GroupColumnsForm.svelte
- assets/svelte/consumers/SinkConsumerForm.svelte
- assets/svelte/databases/Form.svelte
- assets/svelte/http_endpoints/Form.svelte
- assets/svelte/wal_pipelines/Form.svelte
- lib/sequin_web/live/databases/form.ex
- lib/sequin_web/live/http_endpoints/form.ex
- lib/sequin_web/live/sink_consumers/form.ex
- lib/sequin_web/live/sink_consumers/index.ex
- lib/sequin_web/live/wal_pipelines/form.ex
- lib/sequin_web/router.ex
Improve rendering full page forms by removing the Modal/Dialog wrapper that was causing some quirks with some event handling.
Forms:
- Sink
- Database
- HTTP endpoint
- WAL Pipeline
Related additional improvements:
- The new component name is changed from `FullPageModal` to `FullPageForm`
- Simplified external props
- Now we ask for confirmation on exit by default, instead of the opposite. It is still configurable via a prop if needed to override.
- Replaced read only `Popovers` for `Tooltips`. Keep Popovers for cases where we need an additional input. This improves usability as information is shown on hover.
- Fixed Message Group card on Sink form to be expanded by default
- Improved rendering the horizontal scrollbar on `CodeWithCopy` blocks
Shoutout to @acco for the help figuring a …
> fix: improve full page forms to avoid using a modal

- lib/sequin/transforms/transforms.ex
- test/sequin_web/controllers/yaml_controller_test.exs
- test/support/models/character.ex
While testing out CLI export->plan functionality, I detected a couple of issues when trying to load a config from a yaml.
1. `sinks.max_retry_count` - if is set to nil (as it seems its the default) the loader fails with an error stating that it should be greater than 0
2. `sinks.active_backfill` - if is present, and set to any value, the loader fails. I suggest to ignore this field for now until we support managing backfills via the yaml.
3. `http_endpoints.encrypted_headers` - seems to be [serialized as a string/binary](https://github.com/sequinstream/sequin/blob/main/lib/sequin/transforms/transforms.ex#L418-L420) (even if the map is empty, as it seems is the default) - causing to fail `parse_headers` validation. I suggest ignoring this field for now, unless we want to handle …
> fix: improve yaml load for `sinks.max_retry_count`, `sinks.active_backfill` and `http_endpoints.encrypted_headers`

- assets/svelte/cli/Index.svelte
Quick fix for the removal of `brew tap` from the CopyIcon cli installation instructions
cc @acco
> fix: remove the brew tap command from CopyIcon for cli install

- assets/svelte/components/ui/card/expandable-card-header.svelte
- assets/svelte/components/ui/card/expandable-card.svelte
- assets/svelte/consumers/GroupColumnsForm.svelte
- assets/svelte/consumers/SinkConsumerForm.svelte
Improve Message Grouping card with the following changes:
- Always show this card as an ExpandableCard, in order to show the Chevron and keep the layout consistent
- For the Sink Edit form show tooltip with the notice "Message grouping can’t be changed for an active sink." on hover on the entire title bar
- Change default expanded state whenever the card is shown in Sink Creation
Fixes #1383
---
> fix: Message Grouping card form improvements

- lib/sequin/changeset.ex
- lib/sequin/consumers/consumer_event.ex
- lib/sequin/consumers/consumer_event_data.ex
- lib/sequin/consumers/consumer_record.ex
- lib/sequin/consumers/consumer_record_data.ex
- lib/sequin/consumers/consumers.ex
- lib/sequin/postgres/postgres.ex
- test/changeset_test.exs
- test/sequin/consumer_record_test.exs
- test/sequin/consumers_test.exs
* Decimal
* Date
* DateTime
* NaiveDateTime
Resolves: https://github.com/sequinstream/sequin/issues/1465
> 🐛 Fix consumer message serialization of struct types

- assets/svelte/transforms/Edit.svelte
Fix showing missing Function form validation errors that were not being shown because they were accessing the wrong `formErrors` accessor paths.
This caused subsequent DB-related constraint errors (returned by `Repo.insert`) such as "name has already been taken" to not show up, as those validations are not happening in the first place due to the failed initial validations.
This seems to be the expected default behavior as [stated in the docs](https://hexdocs.pm/ecto/Ecto.Changeset.html#module-validations-and-constraints) and even though I would love to see those DB-related errors as soon as possible, it may involve a deeper set of changes and implications.
Additional, unrelated change:
Always show the "Create Function" button on the same spot, to be consistent. Thus moving the Copy to GPT …
> fix: show missing Transform Function form validation errors

- lib/sequin/runtime/slot_message_store.ex
- lib/sequin/runtime/slot_message_store_state.ex
- test/sequin/slot_message_store_state_test.exs
- test/sequin/slot_message_store_test.exs
This behavior is O(messages) whenever a message fails. We don't need this anymore, as we automatically flush stale in-memory messages on an interval.
> ⚡️ Remove State.pop_blocked_messages

- assets/svelte/consumers/ShowMessages.svelte
Fix ternary check to properly display `message.not_visible_until` on Message Detail view
Fixes #1454
> fix: only display message not_visible_until date if its defined

- lib/sequin/databases/postgres_database.ex
This is a temporary workaround to override any PGHOST-related value that might inadvertently set by default
We can revert this once a new Postgrex version >0.20.0 is published
See https://github.com/elixir-ecto/postgrex/pull/742 for more information
> fix: workaround to fix PGHOST-related defaults picked by Postgrex

- assets/svelte/databases/Form.svelte
It seems that due to the use of `push_navigate` on a successful `form_submitted` event the callback receives `null` as a response, rather than `{ok: true}`
So now we just do the opposite check on submission: if the form response is `null` we don't restore to local storage, and if its `{ok: false}` we keep the form in local storage
Fixes #1472
Shoutout to @g14a for the amazing replication video! it was super helpful
--
Pre-fix replication steps:
1. Create two database records
2. Open up one, dont change anything, and click "Update Database" to cause a successful update
3. Open up the other db record, and you should see the polluted form details loaded from local storage
> fix: avoid saving form to local storage if submission was successful

- assets/svelte/databases/Form.svelte
- lib/sequin/databases/postgres_database.ex
- lib/sequin_web/live/databases/form.ex
Only show database exit confirm dialog when form is dirty, using the same implementation as the sink consumer form.
Also set the ssl default value to `true` in the `typed_schema` definition rather than in the `render` fn, as doing `database.ssl || true` always causes the value to be `true` regardless of the existing boolean set in `ssl`
> fix: only show database exit confirm dialog when form is dirty

- lib/sequin/consumers/consumers.ex
- lib/sequin/runtime/consumer_lifecycle_event_worker.ex
Updating db sequences for a sink consumer are performed asynchronously in the ConsumerLifecycleEventWorker.
This leads to a race condition where the sink details are shown before the sequences are updated, resulting in error messages that may be missing schema and table names.
Fixes #1437
> fix: update sequences inline on creating sink consumer to avoid race condition

- lib/sequin/health/kickoff_check_http_endpoint_health_worker.ex
- lib/sequin/health/kickoff_check_postgres_replication_slot_worker.ex
- lib/sequin/health/kickoff_check_sink_configuration_worker.ex
- lib/sequin/runtime/sink_pipeline.ex
Replaced Enum.map with Enum.each since the mapped result wasn't used, to avoid unnecessary list allocation.
> chore: replace Enum.map with Enum.each for side effects

- assets/svelte/consumers/SinkConsumerForm.svelte
- lib/sequin_web/live/components/consumer_form.ex
- lib/sequin_web/live/sink_consumers/form.ex
- lib/sequin_web/live/sink_consumers/show.ex
- lib/sequin_web/router.ex
Unify rendering Sink :new and :edit actions into a single unit of logic, in order to re-use as many components as we can, and also use the same layer without sidebar. Also refactor a couple of things to make things a bit more clear to edit/understand.
Also added the sink name to the title
Fixes #1497 
@g14a thanks for reporting this issue and suggesting improvements! Keep them coming 🙌🏼
> fix: unify consumer sink :new and :edit into a single form live view

- assets/svelte/consumers/SinkIndex.svelte
- lib/sequin/consumers/consumers.ex
- lib/sequin_web/live/sink_consumers/index.ex
- test/sequin/consumers_test.exs
- add paginated query helper for sink consumers
- update sinks index LiveView to fetch pages synchronously on mount and asynchronously on page change
- expose pagination props and controls in `SinkIndex.svelte`
- `mix test` *(fails: Hex not installed)*
- `npm test` in `assets` *(fails: missing script)*
> Implement paginated sinks list

- lib/sequin_web/live/transforms/edit.ex
* the restart occurs in the lifecycle event worker, so is unnecessary
to do it synchronously as well. for customers with large slot trees,
this call takes a while and it impacts FE responsiveness
> 🐛 Don't restart replication synchronously

- scripts/merge.sh
* Deleting the branch is destructive and causes graphite to lose track
of branches in a stack.
If others like to to default to YES, we could instead check graphite state
to `gt sync` instead of `git branch -D`
> ⚙️  Default to NO for delete branch on merge

- lib/sequin/consumers/consumer_event.ex
- lib/sequin/consumers/consumer_event_data.ex
- lib/sequin/consumers/consumer_record.ex
- lib/sequin/consumers/consumer_record_data.ex
- lib/sequin/consumers/consumers.ex
- test/sequin/consumers_test.exs
- test/sequin/slot_message_store_test.exs
* This fixes a bug where record_ and change_serializers were not set
on consumer events/records inserted into the database
The effect of this PR is that all consumer events/records are passed
through changesets before insertion to the database
> 🐛 Serialize events/record through changesets

- lib/sequin/config_parser.ex
- test/sequin/config_parser_test.exs
* SECRET_KEY_BASE does not have to be base674 encoded and can be any
string gte 64 bytes
* VAULT_KEY must be base64 encoded and the decoded string must be gte 32
bytes
> 🐛 Fix constraints on SECRET_KEY_BASE and VAULT_KEY

- lib/sequin/transforms/transforms.ex
- lib/sequin/yaml_loader.ex
- test/sequin/yaml_loader_test.exs
- test/support/factory/functions_factory.ex
* By removing the keys entirely
* If users set `transform: none` they can remove ie. transform WITHOUT
this PR
* Do we want removing the key to lead to removing the function?
> 🐛 Allow removal of transforms, filters, and routing functions

- assets/svelte/functions/Edit.svelte
- assets/svelte/functions/EditableArgument.svelte
- assets/svelte/functions/types.ts
- lib/sequin/consumers/consumers.ex
- lib/sequin/functions/minielixir.ex
- lib/sequin/runtime/message_handler.ex
- lib/sequin_web/live/functions/edit.ex
A pencil is now shown at the right of each attribute that will be passed to the function. If the user clicks on the pencil it transforms into a 
Save and Cancel icons
- For "record", "metadata", "changes" arguments, it converts the text into a CodeMirror instance.
- For the "action" argument, a dropdown is shown instead
Save / Cancel logic:
- If the cancel button is pressed the text is left unchanged and resets the editor/dropdown back to the original value.
- If the save button is pressed, the encoded version is updated in the svelte component, which causes the validation event to occur. Within the validation, the encoded changes are converted into structs, and are injected into the socket assigns for the synthetic and real test messages.
Side notes:
- I did not add a Run Test button as …
> Editable function test messages

- lib/sequin_web/router.ex
- lib/sequin_web/user_auth.ex
- test/sequin_web/user_auth_test.exs
Hello all. Thank you for starting this amazing project in elixir. I started to play around with sequin and decided to start working on some simplest PR first. Apologize if I miss anything.
This PR
- Add :redirect_to option to control where unauthenticated users are sent. Default to login page, with option to redirect to registration
- New pipeline to use this option in order to redirect unauthenticated user to register page
Fixes #1598
> Redirect to signup page if user is not authenticated after vistiting access invite link

- config/config.exs
We expect more aggressive sampling for replication slot size, and so should run this worker more often.
Co-authored-by: Russell McQueeney <249771+fazzone@users.noreply.github.com>
> Reduce time interval of `KickoffCheckPostgresReplicationSlotWorker`

- docs/archive/ingesting-from-postgres.mdx
- docs/connect-postgres.mdx
- docs/reference/databases.mdx
- postgres-replication.md
fixes #1563 
it's confusing because GRANT is in fact `all tables in schema` but create/alter pub is just `tables in schema`
> [docs] fix syntax for schema publication

- assets/svelte/consumers/ShowSinkHeader.svelte
- assets/svelte/consumers/SinkIndex.svelte
- assets/svelte/stores/pageStore.ts
- lib/sequin_web/live/sink_consumers/index.ex
- Update sink consumers index LiveView to handle page query parameter in mount and handle_params
- Add pageStore to maintain current page number across navigation between Index and Show sink components
- Update sink Index to store current page before navigating to details
- Modify back button in Show sink to return to correct page
Fixes #1618
> feat: persist pagination state when navigating to/from sink details

- config/test.exs
- test/sequin/postgres_replication_test.exs
- test/support/factory/test_event_log_factory.ex
- test/support/simple_http_server.ex
Initial implementation for #1359 that validates transaction consistency through webhook events. The system performs multiple row updates in a table, generating update events that are received and validated for correct sequencing via webhooks.
```bash
JEPSEN_TRANSACTIONS_COUNT="100" mix test --only jepsen
```
| Variable | Default | Description |
|----------|---------|-------------|
| `JEPSEN_HTTP_HOST` | "127.0.0.1" | HTTP server host |
| `JEPSEN_HTTP_PORT` | "4040" | HTTP server port |
| `JEPSEN_TRANSACTIONS_COUNT` | 20 | Number of transactions to run |
| `JEPSEN_TRANSACTION_QUERIES_COUNT` | 10 | Number of queries per transaction |
> feat: add webhook integration test

- config/config.exs
Add Oban Plugin [`Oban.Plugins.Pruner`](https://hexdocs.pm/oban/Oban.Plugins.Pruner.html) to clean up completed jobs older than 14 days.
Fixes #1687
> feat: add Oban.Plugins.Pruner to delete completed jobs older than 14 days

- docs/guides/user-webhooks.mdx
- docs/reference/messages.mdx
- lib/sequin/consumers/consumer_event.ex
- lib/sequin/consumers/consumer_event_data.ex
- lib/sequin/consumers/consumers.ex
- lib/sequin/runtime/message_handler.ex
All messages in a transaction share the same `commit_lsn`. The `commit_idx` is the order (index) of a particular message inside of a transaction.
> Include `commit_idx` in `metadata`

- config/runtime.exs
- lib/sequin/logger/redactor.ex
- Add redactor to filter logs
- However, the redactor does not seem to work on deep metadata keys. Remove areas where we pass errors as metadata to logs
> Add redactor for sensitive logs, remove errors from metadata

- test/support/mocks.ex
- test/test_helper.exs
fixes these warnings:
```elixir
warning: Sequin.Sinks.KafkaMock.publish/2 is undefined (module Sequin.Sinks.KafkaMock is not available or is yet to be defined)
│
20 │     @module.publish(consumer, record)
│             ~
│
└─ lib/sequin/sinks/kafka/kafka.ex:20:13: Sequin.Sinks.Kafka.publish/2
warning: Sequin.Sinks.KafkaMock.publish/2 is undefined (module Sequin.Sinks.KafkaMock is not available or is yet to be defined)
│
24 │     @module.publish(consumer, event)
│             ~
│
└─ lib/sequin/sinks/kafka/kafka.ex:24:13: Sequin.Sinks.Kafka.publish/2
warning: Sequin.Sinks.KafkaMock.publish/3 is undefined (module Sequin.Sinks.KafkaMock is not available or is yet to be defined)
│
28 │     @module.publish(consumer, partition, messages)
│             ~
│
└─ …
```
> fix: move KafkaMock into mock.ex to remove warnings about undefined Kafka functions

- lib/sequin/consumers/kafka_sink.ex
This PR enables the `auto_start_producers` option from the brod client. When this option is set, brod will automatically recreate and start a missing producer if it is invoked after termination.
Additional info:
https://hexdocs.pm/brod/brod.html#start_producer/3
https://github.com/kafka4beam/brod/blob/ee6e50c9fbefb4f093833c24c14aaf2ee07f74b6/src/brod_client.erl#L165-L166
> feat: automatically restart kafka producers

- lib/sequin/consumers/consumers.ex
- lib/sequin/posthog.ex
- lib/sequin/telemetry/posthog_reporter.ex
- test/sequin/posthog_reporter_test.exs
1. Fix how we send `consumer_ack` events to PostHog
2. Batch `consumer_ack` events every minute (instead of every 10 seconds)
> Fix telemetry for acknowledged messages 

- assets/svelte/components/FullPageForm.svelte
- assets/svelte/functions/Edit.svelte
Fixes #1781 specifically for the function code editor, and not for the whole FullPageForm component as done by https://github.com/sequinstream/sequin/pull/1783
> fix: only ignore esc keypress for the function code editor

- lib/sequin/postgres/replication_connection.ex
- lib/sequin/runtime/slot_processor_server.ex
- test/sequin/postgres_replication_test.exs
To back-pressure, we can simply not read messages in from the tcp socket. However, we don't own the socket - Postgrex.Protocol does. When we call `handle_copy_recv`, that will flip on `active: :once` on the socket after reading in all messages. So, our easiest strategy is to simply not call `handle_copy_recv` anymore if we're not ready for new messages.
This means to stop the flow, up in `ReplicationConnection`, we flip on buffering to buffer new tcp messages in state. Only when the pipeline indicates it's ready for more do we process the buffer and resume processing tcp messages as they come in.
> :recycle: Buffer messages as opposed to disconnecting

- assets/svelte/consumers/SinkConsumerForm.svelte
- docs/reference/sinks/overview.mdx
- lib/sequin/runtime/kafka_pipeline.ex
- lib/sequin/runtime/message_handler.ex
- lib/sequin/runtime/sink_pipeline.ex
- lib/sequin/runtime/slot_message_store_state.ex
- lib/sequin/runtime/slot_processor_server.ex
- Use smaller, partitioned SlotMessageStores by default
- Tuned buffer sizes to optimal setting
- Increase demand settings for process_message (big impact)
> :zap: Improve default performance

- assets/svelte/http_endpoints/Show.svelte
- lib/sequin/health/check_http_endpoint_health_worker.ex
- lib/sequin/metrics/metrics.ex
- lib/sequin_web/live/http_endpoints/show.ex
This prevents errors such as 415s from downstream http endpoints.
However, this significantly reduces the thoroughness of HTTP Endpoint health checks. The check now passes so long as the hostname is resolvable. Additionally, the avg. latency is now reported as just the time it takes to translate the hostname to an IP address. This often hits local DNS servers, which are typically very fast, rather than the actual HTTP endpoint
> 🤫 do not tcp connect for endpoint health checks

- assets/svelte/components/FilterForm.svelte
- assets/svelte/consumers/SinkConsumerForm.svelte
- assets/svelte/wal_pipelines/Form.svelte
Fix this esbuild-svelte warning showing up when starting the app:
Seems like since commit [ce5e6b7](https://github.com/sequinstream/sequin/commit/ce5e6b7af00bf65154779c91f4372e46d0e21704) we no longer are displaying errors in the `FilterForm` component, so it seems safe to remove the `export` and the corresponding prop being passed from parent components.
```
▲ [WARNING] [plugin esbuild-svelte] FilterForm has unused export property 'errors'. If it is for external
reference only, please consider using `export const errors`
svelte/components/FilterForm.svelte:6:11:
6 │ export let errors;
╵            ~~~~~~
The plugin "esbuild-svelte" was triggered by this import
import-glob:../svelte/**/*.svelte:2:757:
2 │ ...dule11 from '../svelte/components/FilterForm.svelte';import * as...
╵ …
```
> 🔧 Fix esbuild-svelte warning

- assets/svelte/sinks/nats/NatsSinkCard.svelte
Currently the UI crashes if you try loading a NATS sink without a routing function with the following error. This is a quick fix to get the views loading with some details, we can work on showing as many _dynamic_ details as possible (such as table_name or schema_name) later on
```
Uncaught TypeError: Cannot read properties of undefined (reading 'table_name')
at select_block_type (NatsSinkCard.svelte:94:41)
at Array.create_default_slot_188 (NatsSinkCard.svelte:94:51)
at create_slot (utils.js:165:22)
at create_fragment288 (index.ts:1:1)
at init3 (Component.js:148:34)
at new Card_content (card-content.svelte:11:55)
at Array.create_default_slot170 (NatsSinkCard.svelte:109:26)
at create_slot (utils.js:165:22)
at create_fragment293 (card-title.svelte:16:12)
```
> 🐛 Fix NATS routing details in NatsSinkCard

- cli/cli/config_command_test.go
- cli/config/config.go
- cli/config/config_test.go
- cli/go.mod
- cli/go.sum
- cli/testutil/yaml.go
Previously, the cli did not parse yaml and applied env var subst to the entire yaml as a flat string.  
This PR adds a real yaml parser and applies env var substitution in a structure-aware way, so that you can't interpolate into yaml keys, or interpolate in content which would result in malformed yaml.
Finally, with the parser, we can support a file: key on functions, where we will read the file, path relative to our cwd, and pass the content upstream under the code: key as the api expects.
Consider:
- should we keep the file: separate key, or do in-band signaling where we automatically read files into anything that starts with file:// or something?
- should we interpret paths as relative to process cwd, or relative to the location of the yaml file, or both?
closes #1584
> [cli] allow function code to be embedded via `file:` + smarter ENV embed in yaml

- test/sequin/connection_cache_test.exs
Fix some of the tests that often fail during signoff.
1. Appending `_changed` to the database name factory results forces the config to be different, rather than relying on non-deterministic randomness
2. Adding a 1ms sleep addresses a race condition - I couldn't find the root cause but this seems to fix it for now.
Validated running the test file many times - without these changes the tests often fail at the 10th or so attempt
`mix test test/sequin/connection_cache_test.exs --repeat-until-failure 1000`
> 🔧 Fix flaky connection_cache_tests

- assets/svelte/consumers/SinkConsumerForm.svelte
- assets/svelte/sinks/elasticsearch/ElasticsearchSinkForm.svelte
- assets/svelte/sinks/meilisearch/MeilisearchSinkForm.svelte
- assets/svelte/sinks/typesense/TypesenseSinkForm.svelte
- lib/sequin/consumers/typesense_sink.ex
- lib/sequin/runtime/typesense_pipeline.ex
1. Configure Typesense to be default fast
2. Add batching to console for Typesense
3. Add alerts to console for Typesense to (a) warn users if they turn off grouping (b) provide in context information about transforms 👇 
---
This PR enhances Typesense sink consumer configuration and defaults:
- Added Typesense-specific alert messages in SinkConsumerForm.svelte
- Refactored TypesenseSinkForm.svelte to group advanced settings and improve input guidance
- Updated default batch_size and timeout_seconds in typesense_sink.ex
- Lowered batch_timeout in typesense_pipeline.ex for faster batch processing
> Make Typesense to be default fast

- lib/sequin/runtime/gcp_pubsub_pipeline.ex
- lib/sequin/runtime/sink_pipeline.ex
- lib/sequin/sinks/gcp/pubsub.ex
- test/sequin/gcp_pubsub_pipeline_test.exs
- test/sequin/gcp_pubsub_test.exs
- test/sequin/sink_pipeline_test.exs
Unfortunately the Broadway batcher will [include the current message in the batch when the batcher responds with `:emit`](https://github.com/dashbitco/broadway/blob/136bea6786ae1526721a98a93ca9d752543c3a7d/lib/broadway/topology/batcher_stage.ex#L159). This makes it hard to enforce a hard byte size ceiling.
I use the `incoming_bytes` as a buffer as a partial workaround -- but this is not perfect.
Considering a PR upstream to move the `event` to `remaining` instead of `acc` -- curious yalls thoughts!
> ✨ GCP PubSub batch by messages and bytes

- mix.exs
After the changes [we made recently on grouping the verify_on_exit calls](https://github.com/sequinstream/sequin/commit/a3dba292da7ce10cc72296fbe7120a219d798d1f
) we started getting a warning in dev mode:
```
│                                                                                                                                                                                                                              │
│       warning: Hammox.verify_on_exit!/0 is undefined (module Hammox is not available or is yet to be defined). Make sure the module name is correct and has been specified in full (or that an alias has been defined)       │
│       │ …
```
> 🛠️ Remove `test/support` from being compiled in :dev mode

- lib/sequin/consumers/consumers.ex
- test/sequin/transforms_test.exs
Change Retention blocks seem to be missing schema name and table names from exported yaml config.
Diff showing before and after from an export fragment generated using the following:
`sequin config export --show-sensitive`
```diff
change_retentions:
- name: silent_glade_791-rrrrrr
filters: []
actions:
- insert
- update
- delete
source_database: sequin_example_222
destination_database: sequin_example_222
-    source_table_schema:
-    source_table_name:
+    source_table_schema: public
+    source_table_name: accounts
destination_table_schema: public
destination_table_name: sequin_events
```
> 🛠️ Fix exporting schema and table names for change_retentions

- lib/sequin/consumers/consumers.ex
- test/sequin/consumers_test.exs
> 🛠️ prevent 16-byte long strings from being treated as UUID in enrichment process

- docs/reference/configuration.mdx
While looking into HA/Production config for Sequin - I noticed this issue - https://github.com/sequinstream/sequin/issues/1899
Based on the reply to the issue, clustering isn't currently supported by Sequin
Further scrolling of docs show a reference to a missing heading for `Clustering configuration` on the `configuration` page is still present - I'm not entirely certain if this bullet point should reference specific config on this page - perhaps the postgres and/or redis vars? or alternatively - this line _could_ be seen as redundant - but I refer to maintainers! 
Thanks team!
> Docs Update - Remove `clustering` reference
